/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FKoreksiStok.java
 *
 * Created on Jul 17, 2012, 11:06:28 AM
 */
package javariesoft;

import com.eigher.db.barangDao;
import com.eigher.db.loghistoryDao;
import com.eigher.model.loghistory;
import com.erv.db.BarangstokDao;
import com.erv.db.jurnalDao;
import com.erv.db.koneksi;
import com.erv.db.rincijurnalDao;
import com.erv.db.stokDao;
import com.erv.function.JDBCAdapter;
import com.erv.function.Util;
import com.erv.fungsi.DecimalFormatRenderer;
import com.erv.model.Barangstok;
import com.erv.model.barang;
import com.erv.model.jurnal;
import com.erv.model.rincijurnal;
import com.erv.model.stok;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;

/**
 *
 * @author erwadi
 */
public final class FKoreksiStok extends javax.swing.JInternalFrame {

    Connection c;
    Connection cm;
    String kodeakun[];
    String namaAkun[];
    double Tdebet, Tkredit = 0.0;
    Statement stat = null;
    int IDJurnal = 0, IDjrn = 0;
    String aksilog = "";
    loghistory lh;
    loghistoryDao lhdao;
    barang b = null;
    barangDao brgdao = null;
    com.erv.function.Util u = new com.erv.function.Util();
    java.text.DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
    String kodebatch = "";

    /**
     * Creates new form FKoreksiStok
     */
    public FKoreksiStok() {
        initComponents();
        try {
            c = koneksi.getKoneksiJ();
            cm = koneksi.getKoneksiM();
            stat = cm.createStatement();
            buatTabel();
            kosong();
            kosongjurnal();
            lh = new loghistory();
            lhdao = new loghistoryDao();
            b = new barang();
            brgdao = new barangDao(c);
            jScrollPane3.setVisible(false);
            jScrollPane3.setSize(550, 150);
            tglJurnal.setDateFormat(d);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getKodebatch() {
        return kodebatch;
    }

    public void setKodebatch(String kodebatch) {
        this.kodebatch = kodebatch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCool1 = new com.erv.function.PanelCool();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JFormattedTextField();
        txtJumlahBaru = new javax.swing.JFormattedTextField();
        txtHargaBaru = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtKodeJurnal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tglJurnal = new datechooser.beans.DateChooserCombo();
        jLabel9 = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboGrup = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        cboAkun = new javax.swing.JComboBox();
        cboDK = new javax.swing.JComboBox();
        txtBiaya = new javax.swing.JFormattedTextField();
        btnInsert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDebet = new javax.swing.JFormattedTextField();
        txtKredit = new javax.swing.JFormattedTextField();
        txtSelisih = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKodeAkun = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtPersediaan = new javax.swing.JFormattedTextField();
        btnCancel = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        CheckOtomatis = new javax.swing.JCheckBox();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FKoreksiStok.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCool1.setName("panelCool1"); // NOI18N
        panelCool1.setLayout(null);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTable3.setName("jTable3"); // NOI18N
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        panelCool1.add(jScrollPane3);
        jScrollPane3.setBounds(170, 40, 20, 20);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelCool1.add(jLabel1);
        jLabel1.setBounds(350, 50, 120, 15);

        txtKodeBarang.setFont(resourceMap.getFont("txtKodeBarang.font")); // NOI18N
        txtKodeBarang.setText(resourceMap.getString("txtKodeBarang.text")); // NOI18N
        txtKodeBarang.setName("txtKodeBarang"); // NOI18N
        txtKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBarangActionPerformed(evt);
            }
        });
        txtKodeBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeBarangKeyPressed(evt);
            }
        });
        panelCool1.add(txtKodeBarang);
        txtKodeBarang.setBounds(170, 20, 110, 21);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelCool1.add(jLabel2);
        jLabel2.setBounds(20, 20, 130, 16);

        txtNamaBarang.setFont(resourceMap.getFont("txtNamaBarang.font")); // NOI18N
        txtNamaBarang.setText(resourceMap.getString("txtNamaBarang.text")); // NOI18N
        txtNamaBarang.setName("txtNamaBarang"); // NOI18N
        panelCool1.add(txtNamaBarang);
        txtNamaBarang.setBounds(290, 20, 390, 21);

        txtJumlah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtJumlah.setEnabled(false);
        txtJumlah.setFont(resourceMap.getFont("txtJumlah.font")); // NOI18N
        txtJumlah.setName("txtJumlah"); // NOI18N
        panelCool1.add(txtJumlah);
        txtJumlah.setBounds(170, 50, 140, 21);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        panelCool1.add(jLabel4);
        jLabel4.setBounds(20, 230, 130, 16);

        txtHarga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtHarga.setEnabled(false);
        txtHarga.setFont(resourceMap.getFont("txtHarga.font")); // NOI18N
        txtHarga.setName("txtHarga"); // NOI18N
        panelCool1.add(txtHarga);
        txtHarga.setBounds(480, 50, 160, 21);

        txtJumlahBaru.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtJumlahBaru.setFont(resourceMap.getFont("txtJumlahBaru.font")); // NOI18N
        txtJumlahBaru.setName("txtJumlahBaru"); // NOI18N
        txtJumlahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBaruActionPerformed(evt);
            }
        });
        txtJumlahBaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJumlahBaruFocusLost(evt);
            }
        });
        panelCool1.add(txtJumlahBaru);
        txtJumlahBaru.setBounds(170, 90, 140, 21);

        txtHargaBaru.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtHargaBaru.setFont(resourceMap.getFont("txtHargaBaru.font")); // NOI18N
        txtHargaBaru.setName("txtHargaBaru"); // NOI18N
        txtHargaBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBaruActionPerformed(evt);
            }
        });
        txtHargaBaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHargaBaruFocusLost(evt);
            }
        });
        panelCool1.add(txtHargaBaru);
        txtHargaBaru.setBounds(480, 90, 160, 21);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        panelCool1.add(jLabel5);
        jLabel5.setBounds(20, 50, 130, 16);

        jSeparator1.setName("jSeparator1"); // NOI18N
        panelCool1.add(jSeparator1);
        jSeparator1.setBounds(20, 80, 660, 10);

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        panelCool1.add(jLabel6);
        jLabel6.setBounds(20, 90, 100, 16);

        jSeparator2.setName("jSeparator2"); // NOI18N
        panelCool1.add(jSeparator2);
        jSeparator2.setBounds(20, 120, 660, 10);

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jLabel7.foreground")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        panelCool1.add(jLabel7);
        jLabel7.setBounds(350, 90, 120, 15);

        txtKodeJurnal.setFont(resourceMap.getFont("txtKodeJurnal.font")); // NOI18N
        txtKodeJurnal.setText(resourceMap.getString("txtKodeJurnal.text")); // NOI18N
        txtKodeJurnal.setEnabled(false);
        txtKodeJurnal.setName("txtKodeJurnal"); // NOI18N
        panelCool1.add(txtKodeJurnal);
        txtKodeJurnal.setBounds(170, 140, 160, 21);

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        panelCool1.add(jLabel8);
        jLabel8.setBounds(360, 140, 80, 15);

        tglJurnal.setFieldFont(resourceMap.getFont("tglJurnal.dch_combo_fieldFont")); // NOI18N
        panelCool1.add(tglJurnal);
        tglJurnal.setBounds(170, 170, 160, 20);

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setForeground(resourceMap.getColor("jLabel9.foreground")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        panelCool1.add(jLabel9);
        jLabel9.setBounds(20, 170, 130, 16);

        txtDeskripsi.setFont(resourceMap.getFont("txtDeskripsi.font")); // NOI18N
        txtDeskripsi.setText(resourceMap.getString("txtDeskripsi.text")); // NOI18N
        txtDeskripsi.setName("txtDeskripsi"); // NOI18N
        panelCool1.add(txtDeskripsi);
        txtDeskripsi.setBounds(170, 200, 500, 21);

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setForeground(resourceMap.getColor("jLabel10.foreground")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        panelCool1.add(jLabel10);
        jLabel10.setBounds(20, 200, 130, 16);

        cboGrup.setFont(resourceMap.getFont("cboGrup.font")); // NOI18N
        cboGrup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Harta", "Hutang", "Modal", "Pendapatan", "Harga Pokok Penjualan", "Biaya" }));
        cboGrup.setName("cboGrup"); // NOI18N
        cboGrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGrupActionPerformed(evt);
            }
        });
        panelCool1.add(cboGrup);
        cboGrup.setBounds(170, 230, 160, 22);

        jSeparator3.setName("jSeparator3"); // NOI18N
        panelCool1.add(jSeparator3);
        jSeparator3.setBounds(20, 260, 660, 10);

        cboAkun.setFont(resourceMap.getFont("cboAkun.font")); // NOI18N
        cboAkun.setName("cboAkun"); // NOI18N
        panelCool1.add(cboAkun);
        cboAkun.setBounds(20, 270, 290, 22);

        cboDK.setFont(resourceMap.getFont("cboDK.font")); // NOI18N
        cboDK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debet", "Kredit" }));
        cboDK.setName("cboDK"); // NOI18N
        panelCool1.add(cboDK);
        cboDK.setBounds(320, 270, 100, 22);

        txtBiaya.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtBiaya.setFont(resourceMap.getFont("txtBiaya.font")); // NOI18N
        txtBiaya.setName("txtBiaya"); // NOI18N
        txtBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiayaActionPerformed(evt);
            }
        });
        panelCool1.add(txtBiaya);
        txtBiaya.setBounds(430, 270, 170, 22);

        btnInsert.setFont(resourceMap.getFont("btnInsert.font")); // NOI18N
        btnInsert.setIcon(resourceMap.getIcon("btnInsert.icon")); // NOI18N
        btnInsert.setText(resourceMap.getString("btnInsert.text")); // NOI18N
        btnInsert.setName("btnInsert"); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        panelCool1.add(btnInsert);
        btnInsert.setBounds(20, 300, 100, 25);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelCool1.add(jButton1);
        jButton1.setBounds(125, 300, 100, 25);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelCool1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 660, 140);

        txtDebet.setFont(resourceMap.getFont("txtDebet.font")); // NOI18N
        txtDebet.setName("txtDebet"); // NOI18N
        txtDebet.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDebetCaretUpdate(evt);
            }
        });
        panelCool1.add(txtDebet);
        txtDebet.setBounds(350, 490, 160, 30);

        txtKredit.setFont(resourceMap.getFont("txtKredit.font")); // NOI18N
        txtKredit.setName("txtKredit"); // NOI18N
        txtKredit.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKreditCaretUpdate(evt);
            }
        });
        panelCool1.add(txtKredit);
        txtKredit.setBounds(520, 490, 160, 30);

        txtSelisih.setFont(resourceMap.getFont("txtSelisih.font")); // NOI18N
        txtSelisih.setName("txtSelisih"); // NOI18N
        panelCool1.add(txtSelisih);
        txtSelisih.setBounds(520, 525, 160, 30);

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setForeground(resourceMap.getColor("jLabel11.foreground")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        panelCool1.add(jLabel11);
        jLabel11.setBounds(440, 535, 70, 14);

        txtKodeAkun.setFont(resourceMap.getFont("txtKodeAkun.font")); // NOI18N
        txtKodeAkun.setText(resourceMap.getString("txtKodeAkun.text")); // NOI18N
        txtKodeAkun.setName("txtKodeAkun"); // NOI18N
        txtKodeAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeAkunActionPerformed(evt);
            }
        });
        panelCool1.add(txtKodeAkun);
        txtKodeAkun.setBounds(340, 230, 180, 21);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setIcon(resourceMap.getIcon("jButton2.icon")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelCool1.add(jButton2);
        jButton2.setBounds(20, 490, 150, 40);

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setForeground(resourceMap.getColor("jLabel12.foreground")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        panelCool1.add(jLabel12);
        jLabel12.setBounds(20, 140, 130, 16);

        txtPersediaan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtPersediaan.setFont(resourceMap.getFont("txtPersediaan.font")); // NOI18N
        txtPersediaan.setName("txtPersediaan"); // NOI18N
        panelCool1.add(txtPersediaan);
        txtPersediaan.setBounds(480, 140, 160, 21);

        btnCancel.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnCancel.setIcon(resourceMap.getIcon("btnCancel.icon")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelCool1.add(btnCancel);
        btnCancel.setBounds(240, 300, 110, 25);

        btnKeluar.setFont(resourceMap.getFont("btnKeluar.font")); // NOI18N
        btnKeluar.setIcon(resourceMap.getIcon("btnKeluar.icon")); // NOI18N
        btnKeluar.setText(resourceMap.getString("btnKeluar.text")); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelCool1.add(btnKeluar);
        btnKeluar.setBounds(360, 300, 110, 25);

        CheckOtomatis.setFont(resourceMap.getFont("CheckOtomatis.font")); // NOI18N
        CheckOtomatis.setText(resourceMap.getString("CheckOtomatis.text")); // NOI18N
        CheckOtomatis.setName("CheckOtomatis"); // NOI18N
        panelCool1.add(CheckOtomatis);
        CheckOtomatis.setBounds(490, 300, 140, 25);

        getContentPane().add(panelCool1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 715, 606);
    }// </editor-fold>//GEN-END:initComponents

private void cboGrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGrupActionPerformed
// TODO add your handling code here:
    isiCombo();
}//GEN-LAST:event_cboGrupActionPerformed

private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
    try {
//        if (cboAkun.getSelectedItem().toString().equals("")) {
//            JOptionPane.showMessageDialog(null, "Akun Perkiraan Tidak Boleh Kosong.. !");
//            txtKodeAkun.requestFocus();
//        } else {
//            if (cekPerkiraan(cm, kodeakun[cboAkun.getSelectedIndex()])==1) {
//                JOptionPane.showMessageDialog(null, "Akun Perkiraan ini Sudah Dientrikan.. !");
//                txtKodeAkun.requestFocus();
//            } else {
        if (CheckOtomatis.isSelected()) {
            tambahjurnal();
        } else {
            if (cboDK.getSelectedIndex() == 0) {
                stat.execute("insert into rinciJurnal values('" + kodeakun[cboAkun.getSelectedIndex()] + "','" + namaAkun[cboAkun.getSelectedIndex()] + "'," + Double.parseDouble(txtBiaya.getValue().toString()) + ",0)");
            } else {
                stat.execute("insert into rinciJurnal values('" + kodeakun[cboAkun.getSelectedIndex()] + "','" + namaAkun[cboAkun.getSelectedIndex()] + "',0," + Double.parseDouble(txtBiaya.getValue().toString()) + ")");
            }
            reloadData();
        }
//            }
//        }
    } catch (Exception e) {
        System.out.println("errror1 " + e);
    }
}//GEN-LAST:event_btnInsertActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        // TODO add your handling code here:
        stat.execute("delete from rinciJurnal where KODEAKUN='" + jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString() + "'");
        reloadData();
    } catch (SQLException ex) {
        Logger.getLogger(FormJurnal.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jTable1MouseClicked

private void txtDebetCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDebetCaretUpdate
// TODO add your handling code here:
    //txtSelisih.setValue(Double.parseDouble(txtDebet.getValue().toString()) - Double.parseDouble(txtKredit.getValue().toString()));
}//GEN-LAST:event_txtDebetCaretUpdate

private void txtKreditCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKreditCaretUpdate
// TODO add your handling code here:
    //
}//GEN-LAST:event_txtKreditCaretUpdate

private void jTable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == 10) {
        try {
            barang b = new barang();
            b = new barangDao(c).getDetails(jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());
            Barangstok bs = BarangstokDao.getDetailKodeBarang(c, b.getKODEBARANG());
            txtKodeBarang.setText(b.getKODEBARANG());
            txtNamaBarang.setText(b.getNAMABARANG());
            txtJumlah.setValue(bs.getSTOK());
            txtHarga.setValue(bs.getCOGS());
            txtJumlahBaru.setValue(bs.getSTOK());
            txtHargaBaru.setValue(bs.getCOGS());
            setKodebatch((jTable3.getValueAt(jTable3.getSelectedRow(), 4)==null)?"":jTable3.getValueAt(jTable3.getSelectedRow(), 4).toString());
            txtPersediaan.setValue(getPersediaan((Integer) txtJumlah.getValue(), (Integer) txtJumlahBaru.getValue(), (Double) txtHargaBaru.getValue()));
            jScrollPane3.setVisible(false);
            txtJumlahBaru.requestFocus();
        } catch (Exception ex) {
            System.out.println("errror " + ex);
        }
    }
}//GEN-LAST:event_jTable3KeyPressed

private void txtKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBarangActionPerformed
// TODO add your handling code here:
    jScrollPane3.setVisible(true);
    JDBCAdapter ja = new JDBCAdapter(c);
    String sql = "select BARANG.KODEBARANG,"
            + "BARANG.NAMABARANG,"
            + "bs.COGS, "
            + "CASEWHEN(KODEBATCH is null,bs.STOK,bsb.STOK) as STOK,"
            + "bsb.KODEBATCH , "
            + "bsb.EXPIRE,"
            + "bs.HARGAJUAL as `Jual` "
            + "from BARANG,JENISBARANG,KATEGORI "
            + "inner join BARANGSTOK bs on bs.KODEBARANG=BARANG.KODEBARANG "
            + "left join BARANGSTOKBATCH bsb on bs.ID=bsb.IDBARANGSTOK "
            + "where BARANG.IDJENIS=JENISBARANG.ID "
            + "AND BARANG.IDKATEGORI=KATEGORI.IDKATEGORI "
            + "AND (BARANG.KODEBARANG like '" + txtKodeBarang.getText() + "%' "
            + "OR lower(BARANG.NAMABARANG) like '%" + txtKodeBarang.getText().toLowerCase() + "%' "
            + "OR bsb.KODEBATCH like '%" + txtKodeBarang.getText() + "%')";
    //ja.executeQuery("select KODEBARANG,NAMABARANG,COGS, STOK from BARANG where KODEBARANG like '" + txtKodeBarang.getText() + "%' or lower(NAMABARANG) like '%" + txtKodeBarang.getText().toLowerCase() + "%'");
    ja.executeQuery(sql);
    jScrollPane3.getViewport().remove(jTable3);
    jTable3 = new JTable(ja);
    jTable3.addKeyListener(new java.awt.event.KeyAdapter() {

        @Override
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTable3KeyPressed(evt);
        }
    });
    TableColumn col = jTable3.getColumnModel().getColumn(0);
    col.setPreferredWidth(40);
    col = jTable3.getColumnModel().getColumn(1);
    col.setPreferredWidth(150);
    col = jTable3.getColumnModel().getColumn(2);
    col.setPreferredWidth(90);
    col = jTable3.getColumnModel().getColumn(3);
    col.setPreferredWidth(40);
    jTable3.setFont(new Font("Tahoma", Font.BOLD, 12));
    jScrollPane3.getViewport().add(jTable3);
    jScrollPane3.repaint();
}//GEN-LAST:event_txtKodeBarangActionPerformed

private void txtKodeBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeBarangKeyPressed
// TODO add your handling code here:
    System.out.print(evt.getKeyCode());
    if (evt.getKeyCode() == 40) {
        jScrollPane3.setVisible(true);
        jTable3.requestFocus();
        jTable3.getSelectionModel().setSelectionInterval(0, 0);
    }
    if (evt.getKeyCode() == 27) {
        jScrollPane3.setVisible(false);
    }
}//GEN-LAST:event_txtKodeBarangKeyPressed

private void txtKodeAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeAkunActionPerformed
// TODO add your handling code here:
    isiCombo1();
}//GEN-LAST:event_txtKodeAkunActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    try {
        int x = JOptionPane.showConfirmDialog(this, "Apakah Data Disimpan?", "", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            if ((txtDeskripsi.getText().equals("")) || (Double.parseDouble(txtSelisih.getValue().toString()) != 0.00)) {
                JOptionPane.showMessageDialog(null, "Data Tidak Benar.. !");
                txtDeskripsi.requestFocus();
            } else {
                String tgl[] = Util.split(tglJurnal.getText(), "-");
                String per = tgl[0] + "." + Integer.parseInt(tgl[1]);
                if (cekperiodeAda(per)) {
                    if (cekperiode(per)) {
                        aksilog = "InsertJurnal";
                        prosesInsert();
                        prosesUpdateLog();
                        kosong();
                        kosongjurnal();
                        hapusTabel();
                        buatTabel();
                        reloadData();
                    } else {
                        JOptionPane.showMessageDialog(null, "Transaksi Untuk Periode Ini Sudah Di Tutup.. !");
                        txtDeskripsi.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Transaksi Untuk Periode Ini Belum Dibuka.. !");
                    txtDeskripsi.requestFocus();
                }
            }
        } else {
            txtDeskripsi.requestFocus();
        }
    } catch (Exception e) {
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void txtJumlahBaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahBaruFocusLost
// TODO add your handling code here:
    // txtPersediaan.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()),Integer.parseInt(txtJumlahBaru.getValue().toString()),Double.parseDouble(txtHargaBaru.getValue().toString())));
    if (getTextInteger(txtJumlahBaru) < 0) {
        JOptionPane.showMessageDialog(null, "Jumlah Baru Tidak Boleh Minus.. !");
        txtJumlahBaru.requestFocus();
    } else if (getTextInteger(txtJumlahBaru) == getTextInteger(txtJumlah)) {
        txtHargaBaru.requestFocus();
        txtPersediaan.setValue(getPersediaanHarga(Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHarga.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
        txtBiaya.setValue(getPersediaanHarga(Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHarga.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
    } else {
        txtHargaBaru.requestFocus();
        txtPersediaan.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()), Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
        txtBiaya.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()), Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
    }
}//GEN-LAST:event_txtJumlahBaruFocusLost

private void txtHargaBaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHargaBaruFocusLost
// TODO add your handling code here:
    if (getFormatTextDouble(txtHargaBaru) < 0) {
        JOptionPane.showMessageDialog(null, "Harga Baru Tidak Boleh Minus.. !");
        txtJumlahBaru.requestFocus();
    } else if (getTextInteger(txtJumlahBaru) == getTextInteger(txtJumlah)) {
        txtDeskripsi.requestFocus();
        txtPersediaan.setValue(getPersediaanHarga(Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHarga.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
        txtBiaya.setValue(getPersediaanHarga(Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHarga.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
    } else {
        //txtDeskripsi.requestFocus();
        txtPersediaan.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()), Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
        txtBiaya.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()), Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
    }
//    txtPersediaan.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()), Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
//    txtBiaya.setValue(getPersediaan(Integer.parseInt(txtJumlah.getValue().toString()), Integer.parseInt(txtJumlahBaru.getValue().toString()), Double.parseDouble(txtHargaBaru.getValue().toString())));
}//GEN-LAST:event_txtHargaBaruFocusLost

private void txtJumlahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBaruActionPerformed
// TODO add your handling code here:
    txtHargaBaru.requestFocus();
}//GEN-LAST:event_txtJumlahBaruActionPerformed

private void txtHargaBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBaruActionPerformed
// TODO add your handling code here:
    txtDeskripsi.requestFocus();
}//GEN-LAST:event_txtHargaBaruActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        kosong();
        kosongjurnal();
        hapusTabel();
        buatTabel();
        reloadData();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiayaActionPerformed
        // TODO add your handling code here:
        btnInsert.requestFocus();
    }//GEN-LAST:event_txtBiayaActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            // TODO add your handling code here:
            stat.close();
            cm.close();
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    void isiCombo() {
        cboAkun.removeAllItems();
        //cboBank.removeAllItems();
        Statement stat1 = null;
        String sql = "select * from PERKIRAAN where (TIPE='D' or TIPE='SD') and GRUP=" + (cboGrup.getSelectedIndex() + 1) + " order by 2";
        try {
            stat1 = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat1.executeQuery(sql);
            int j = 0;
            if (rs.last()) {
                j = rs.getRow();
            }
            if (j > 0) {
                kodeakun = new String[j];
                namaAkun = new String[j];
                rs.beforeFirst();
                int c2 = 0;
                while (rs.next()) {
                    cboAkun.addItem(rs.getString(1) + "-" + rs.getString(2));
                    kodeakun[c2] = rs.getString(1);
                    namaAkun[c2] = rs.getString(2);
                    c2++;
                }
            }//            
        } catch (SQLException ex) {
            Logger.getLogger(FormJurnal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                stat1.close();
            } catch (SQLException ex) {
                Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    void isiCombo1() {
        cboAkun.removeAllItems();
        //cboBank.removeAllItems();
        String sql = "select * from PERKIRAAN where (TIPE='D' or TIPE='SD') and (kodeperkiraan like '" + txtKodeAkun.getText() + "%' OR lower(NAMAPERKIRAAN) like '" + txtKodeAkun.getText().toLowerCase() + "%') order by 2";
        try {
            Statement stat1 = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat1.executeQuery(sql);
            int j = 0;
            if (rs.last()) {
                j = rs.getRow();
            }
            if (j > 0) {
                kodeakun = new String[j];
                namaAkun = new String[j];
                rs.beforeFirst();
                int c1 = 0;
                while (rs.next()) {
                    cboAkun.addItem(rs.getString(1) + "-" + rs.getString(2));
                    kodeakun[c1] = rs.getString(1);
                    namaAkun[c1] = rs.getString(2);
                    c1++;
                }
            }
            stat1.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormJurnal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void reloadData() {
        JDBCAdapter j = new JDBCAdapter(cm);
        j.executeQuery("select * from rinciJurnal");
        jScrollPane1.getViewport().remove(jTable1);
        jTable1 = new JTable(j);
        jTable1.setFont(new Font("Tahoma", Font.BOLD, 12));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setFocusable(false);
        jTable1.setFocusable(false);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new DecimalFormatRenderer());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new DecimalFormatRenderer());
        jTable1.setFont(new Font("Tahoma", Font.BOLD, 11));
        jScrollPane1.getViewport().add(jTable1);
        jScrollPane1.repaint();
        try {
            Tdebet = 0;
            Tkredit = 0;
            ResultSet rs = stat.executeQuery("select * from rinciJurnal");
            while (rs.next()) {
                //System.out.println(rs.getString(3) + "--- "+rs.getString(4));
                Tdebet += toDesimal(rs.getDouble(3));
                Tkredit += toDesimal(rs.getDouble(4));
                txtDebet.setValue(toDesimal(Tdebet));
                txtKredit.setValue(toDesimal(Tkredit));
            }
            double selisih = toDesimal(Tdebet) - toDesimal(Tkredit);
            //double selisih = Double.parseDouble(txtDebet.getValue().toString()) - Double.parseDouble(txtKredit.getValue().toString());
            txtSelisih.setValue(selisih);
            //System.out.println(Tdebet + "--- "+toDesimal(Tkredit) +" ="+toDesimal(selisih));
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormJurnal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            j.close();
        } catch (SQLException ex) {
            Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static double toDesimal(double a) {
        DecimalFormat df = new DecimalFormat("###.00");
        return Double.parseDouble(df.format(a));
    }

    void buatTabel() {
        String sqlCreate = "create table rinciJurnal (KODEAKUN varchar(20),PERKIRAAN varchar(50), "
                + "DEBET double, "
                + "KREDIT double)";
        try {
            stat.execute(sqlCreate);
        } catch (SQLException ex) {
            Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hapusTabel() {
        try {
            stat.execute("drop table rinciJurnal");
        } catch (SQLException ex) {
        }
    }

    void kosong() {
        txtKodeBarang.setText("");
        txtNamaBarang.setText("");
        txtJumlah.setText("0");
        txtHarga.setText("0");
        txtJumlahBaru.setText("0");
        txtHargaBaru.setText("0");
        txtBiaya.setText("0");
        txtKodeBarang.requestFocus();
    }

    void kosongjurnal() {
        txtKodeJurnal.setText("");
        txtDeskripsi.setText("Koreksi Stok Awal");
        txtKodeAkun.setText("");
        txtBiaya.setText("");
        txtPersediaan.setText("");
        txtDebet.setText("");
        txtKredit.setText("");
        txtSelisih.setText("");
        cboDK.setSelectedIndex(0);
        setKodeJurnal();
    }

    void setKodeJurnal() {
        String tgl = com.erv.function.Util.toDateStringSql(new Date());
        try {
            IDJurnal = jurnalDao.getIDJurnal(c);
            txtKodeJurnal.setText("KR" + com.erv.function.Util.getbln(tgl) + com.erv.function.Util.getthn(tgl) + IDJurnal);
        } catch (SQLException ex) {
            Logger.getLogger(FormPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public double getFormatTextDouble(JFormattedTextField t) {
        double h = 0;
        if (t.getValue() != null) {
            h = Double.parseDouble(t.getValue().toString());
        }
        return h;
    }

    public double getTextDouble(JTextField t) {
        double h = 0;
        if (t.getText() != null) {
            h = Double.parseDouble(t.getText());
        }
        return h;
    }

    public int getTextInteger(JTextField t) {
        int h = 0;
        if (t != null) {
            h = Integer.parseInt(t.getText());
        }
        return h;
    }

    public boolean cekperiode(String periode) throws SQLException {
        //String periode = thn + "." + bln;
        boolean hasil1 = false;
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("select * from KONTROLPERIODE where PERIODE='" + periode + "' and STATUSSTOK='1'");
        if (rs.next()) {
            if (rs.getString(1) != null) {
                hasil1 = true;
            }
        }
        rs.close();
        s.close();
        return hasil1;
    }

    public boolean cekperiodeAda(String bul) throws SQLException {
        //String periode = thn + "." + bln;
        boolean ada = false;
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("select * from KONTROLPERIODE where PERIODE='" + bul + "'");
        if (rs.next()) {
            if (rs.getString(1) != null) {
                ada = true;
            }
        }
        rs.close();
        s.close();
        return ada;
    }

    void prosesUpdateLog() {
        //java.sql.Date tanggallog;
        String tanggallog;
        String jamlog = u.jamsekarang + ":" + u.menitsekarang + ":" + u.detiksekarang;
        //tanggallog = java.sql.Date.valueOf(u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang);
        tanggallog = u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang;
        try {
            String ketlog = "";
            lh.setUSERIDENTITY(JavarieSoftApp.jenisuser);
            lh.setTANGGAL(tanggallog);
            lh.setJAM(jamlog);
            lh.setTABEL("TJURNAL");
            lh.setNOREFF(txtKodeJurnal.getText());
            lh.setAKSI(aksilog);
            if (aksilog.equals("InsertJurnal")) {
                ketlog = "Insert Data Jurnal " + txtKodeJurnal.getText() + " Tanggal " + java.sql.Date.valueOf(tglJurnal.getText()) + " Deskripsi " + txtDeskripsi.getText();
            } else if (aksilog.equals("Update")) {
                ketlog = "Update Data Jurnal " + txtKodeJurnal.getText();
            } else if (aksilog.equals("Delete")) {
                ketlog = "Delete Data Jurnal " + txtKodeJurnal.getText();
            }
            lh.setKETERANGAN(ketlog);
            lhdao.insert(c, lh);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
    }

    void prosesInsert() {
        String tgl = com.erv.function.Util.toDateStringSql(new Date());
        String kdjrn = "";
        try {
//            IDJurnal = jurnalDao.getIDJurnal(c);
//            txtKodeJurnal.setText("KR" + com.erv.function.Util.getbln(tgl) + com.erv.function.Util.getthn(tgl) + IDJurnal);

//            int idtemp = jurnalDao.getIDJurnal(c);
//            if (idtemp >= IDJurnal) {
            c.createStatement().execute("set autocommit false");
            IDjrn = jurnalDao.getIDJurnal(c);
            kdjrn = "KR" + com.erv.function.Util.getbln(tgl) + com.erv.function.Util.getthn(tgl) + IDJurnal;

            stok s = new stok();
            jurnal j = new jurnal();

            int jumlah = Integer.parseInt(txtJumlah.getText());
            int jumlahBaru = Integer.parseInt(txtJumlahBaru.getText());
            double hrglama = Double.parseDouble(txtHarga.getValue().toString());
            double hrgbaru = Double.parseDouble(txtHargaBaru.getValue().toString());
            s.setIDPENJUALAN(getIDKoreksi());
            s.setKODEBARANG(txtKodeBarang.getText());
            s.setTANGGAL(tglJurnal.getText());
            s.setIN((jumlahBaru < jumlah) ? 0 : (jumlahBaru - jumlah));
            s.setOUT((jumlahBaru < jumlah) ? (jumlah - jumlahBaru) : 0);
            s.setKODETRANS("Z");
            s.setKODEBATCH(getKodebatch());
            //j.setID(IDJurnal);
            j.setID(IDjrn);
            j.setKODEJURNAL(kdjrn);
            //j.setKODEJURNAL(txtKodeJurnal.getText());
            j.setTANGGAL(tglJurnal.getText());
            j.setDESKRIPSI(txtDeskripsi.getText());

            Statement st = cm.createStatement();
            ResultSet rs;
            if (jumlah == jumlahBaru) {
                jurnalDao.insertIntoJURNAL(c, j);
                String sql = "update barangstok set COGS=? where KODEBARANG=?";
                PreparedStatement statement = c.prepareStatement(sql);
                statement.setDouble(1, Double.parseDouble(txtHargaBaru.getValue().toString()));
                statement.setString(2, txtKodeBarang.getText());
                statement.executeUpdate();
                statement.close();

                rs = st.executeQuery("select * from rinciJurnal");
                rincijurnal r = new rincijurnal();
                int count=1;
                while (rs.next()) {
                    r.setKODEJURNAL("" + IDJurnal);
                    r.setKODEPERKIRAAN(rs.getString(1));
                    r.setDEBET(rs.getDouble(3));
                    r.setKREDIT(rs.getDouble(4));
                    r.setNO(count);
                    r.setREF(""); 
                    rincijurnalDao.insertIntoRINCIJURNAL(c, r);
                }
            } else if ((jumlah != jumlahBaru) && (hrglama != hrgbaru)) {
                stokDao.insertIntoSTOK(c, s);
                jurnalDao.insertIntoJURNAL(c, j);
                String sql = "update barangstok set COGS=? where KODEBARANG=?";
                PreparedStatement statement = c.prepareStatement(sql);
                statement.setDouble(1, Double.parseDouble(txtHargaBaru.getValue().toString()));
                statement.setString(2, txtKodeBarang.getText());
                statement.executeUpdate();
                statement.close();

                rs = st.executeQuery("select * from rinciJurnal");
                rincijurnal r = new rincijurnal();
                int count=0;
                while (rs.next()) {
                    r.setKODEJURNAL("" + IDJurnal);
                    r.setKODEPERKIRAAN(rs.getString(1));
                    r.setDEBET(rs.getDouble(3));
                    r.setKREDIT(rs.getDouble(4));
                    r.setNO(count);
                    r.setREF("");
                    rincijurnalDao.insertIntoRINCIJURNAL(c, r);
                }
            } else {
                stokDao.insertIntoSTOK(c, s);
                jurnalDao.insertIntoJURNAL(c, j);
                //Statement st = cm.createStatement();
                rs = st.executeQuery("select * from rinciJurnal");
                rincijurnal r = new rincijurnal();
                int count=1;
                while (rs.next()) {
                    r.setKODEJURNAL("" + IDJurnal);
                    r.setKODEPERKIRAAN(rs.getString(1));
                    r.setDEBET(rs.getDouble(3));
                    r.setKREDIT(rs.getDouble(4));
                    r.setNO(count);
                    r.setREF(""); 
                    rincijurnalDao.insertIntoRINCIJURNAL(c, r);
                    count++;
                }
            }
            c.commit();
            JOptionPane.showMessageDialog(null, "Koreksi Data Ok");
            kosong();
            kosongjurnal();
            rs.close();
            st.close();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        } catch (SQLException ex) {
            try {
                c.rollback();
                JOptionPane.showMessageDialog(this, "Rollback :"+ex.toString());
            } catch (SQLException ex1) {
                Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } finally {
            try {
                c.createStatement().execute("set autocommit true");
            } catch (SQLException ex) {
                Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    int getIDKoreksi() {
        int temp = 1;
        try {
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("SELECT max(IDPENJUALAN) FROM STOK where KODETRANS='Z'");
            if (r.next()) {
                if (r.getString(1) != null) {
                    temp = r.getInt(1) + 1;
                }
            }
            r.close();
            s.close();
        } catch (SQLException ex) {
            Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
        }
        return temp;
    }

    double getPersediaan(int jumlah, int jumlahbaru, double harga) {
        double tot = 0;
        if (jumlahbaru > jumlah) {
            tot = (jumlahbaru - jumlah) * harga;
        } else {
            tot = (jumlah - jumlahbaru) * harga;
        }
        return tot;
    }

    double getPersediaanHarga(int jumlahbaru, double hargalama, double hargabaru) {
        double tot = 0;
        if (hargabaru > hargalama) {
            tot = (hargabaru - hargalama) * jumlahbaru;
        } else {
            tot = (hargalama - hargabaru) * jumlahbaru;
        }
        return tot;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckOtomatis;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JComboBox cboAkun;
    private javax.swing.JComboBox cboDK;
    private javax.swing.JComboBox cboGrup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private com.erv.function.PanelCool panelCool1;
    private datechooser.beans.DateChooserCombo tglJurnal;
    private javax.swing.JFormattedTextField txtBiaya;
    private javax.swing.JFormattedTextField txtDebet;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JFormattedTextField txtHarga;
    private javax.swing.JFormattedTextField txtHargaBaru;
    private javax.swing.JFormattedTextField txtJumlah;
    private javax.swing.JFormattedTextField txtJumlahBaru;
    private javax.swing.JTextField txtKodeAkun;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtKodeJurnal;
    private javax.swing.JFormattedTextField txtKredit;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JFormattedTextField txtPersediaan;
    private javax.swing.JFormattedTextField txtSelisih;
    // End of variables declaration//GEN-END:variables

    void tambahjurnal() {
        try {
            String akunpersediaan = "", akunmodalsetor = "";
            Statement s;
            s = cm.createStatement();
            s.execute("set autocommit false");
//            try {
//                p = dbperkiraan.getDetails("11310");
//                akunpersediaan = p.getNAMAPERKIRAAN();
//                p = dbperkiraan.getDetails("31101");
//                akunmodalsetor = p.getNAMAPERKIRAAN();
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
//            }
            int jumlah = Integer.parseInt(txtJumlah.getText());
            int jumlahBaru = Integer.parseInt(txtJumlahBaru.getText());
            double Hmodal = Double.parseDouble(txtHarga.getText());
            double Hmodalbaru = Double.parseDouble(txtHargaBaru.getText());
            if (jumlah < jumlahBaru || Hmodal < Hmodalbaru) {
                s.addBatch("insert into rinciJurnal values('11310','PERSEDIAAN BARANG DAGANGAN'," + Double.parseDouble(txtBiaya.getValue().toString()) + ",0)");
                s.addBatch("insert into rinciJurnal values('31101','MODAL DISETOR',0," + Double.parseDouble(txtBiaya.getValue().toString()) + ")");
                s.executeBatch();
            } else {
                s.addBatch("insert into rinciJurnal values('31101','MODAL DISETOR'," + Double.parseDouble(txtBiaya.getValue().toString()) + ",0)");
                s.addBatch("insert into rinciJurnal values('11310','PERSEDIAAN BARANG DAGANGAN',0," + Double.parseDouble(txtBiaya.getValue().toString()) + ")");
                s.executeBatch();
            }
            c.commit();
            s.execute("set autocommit true");
            s.close();
            reloadData();
        } catch (SQLException ex) {
            try {
                c.rollback();
                JOptionPane.showMessageDialog(null, "Rollback Gagal.. !"+ex.toString());
            } catch (SQLException ex1) {
                //JOptionPane.showMessageDialog(null, "Jurnal Ok.. !");
            }
//            Logger.getLogger(FKoreksiStok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean cekPerkiraan(Connection cm, int kode) {
        boolean hasil = false;
        try {
            Statement st = cm.createStatement();
            ResultSet rs = st.executeQuery("select KODEAKUN from rincijurnal where KODEAKUN='" + kode + "'");
            if (rs.next()) {
                if (rs.getString(1) != null) {
                    hasil = true;
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }

        return hasil;
    }
}
