/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPembelian.java
 *
 * Created on Nov 23, 2011, 1:01:49 PM
 */
package javariesoft;

import com.erv.db.koneksi;
import com.erv.function.JDBCAdapter;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import com.eigher.db.loghistoryDao;
import com.eigher.model.loghistory;
import com.erv.db.KontrolTanggalDao;
import com.erv.function.Util;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author erwadi
 */
public class FormPembelian extends javax.swing.JInternalFrame {

    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    java.text.DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
    loghistory lh;
    loghistoryDao lhdao;
    com.erv.function.Util u = new com.erv.function.Util();
    String aksilog = "";
    Connection c = null;

    /**
     * Creates new form FormPembelian
     */
    public FormPembelian() {
        initComponents();
        try {
            c = koneksi.getKoneksiJ();
        } catch (SQLException ex) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
        lh = new loghistory();
        lhdao = new loghistoryDao();
        setLayar();
        isiCombo();
        setSize(dim.width, dim.height);
        setLocation(0, 0);
        tglTransaksi.setDateFormat(d);
        if (JavarieSoftApp.groupuser.equals("Pembelian")) {
            btnBayarPenerimaanHutang.setVisible(false);
            btnDeletePembelianAll.setVisible(false);
            btnview.setVisible(false);
        } else if (JavarieSoftApp.groupuser.equals("KaGudang")) {
            btnBayarPenerimaanHutang.setVisible(false);
            btnDeletePembelianAll.setVisible(false);
            btnview.setVisible(true);
        } else if (JavarieSoftApp.groupuser.equals("Administrator")) {
            btnBayarPenerimaanHutang.setVisible(true);
            btnDeletePembelianAll.setVisible(false);
            btnview.setVisible(true);
        } else if (JavarieSoftApp.groupuser.equals("Operator")) {
            btnBayarPenerimaanHutang.setVisible(false);
            btnDeletePembelianAll.setVisible(false);
            btnview.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCool2 = new com.erv.function.PanelCool();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDeletePembelianAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKriteria = new com.erv.function.TextFieldCool();
        cbokriteria = new javax.swing.JComboBox();
        tglTransaksi = new datechooser.beans.DateChooserCombo();
        btnFilter = new javax.swing.JButton();
        cboStatus = new javax.swing.JComboBox();
        btnview = new javax.swing.JButton();
        btnBayarPenerimaanHutang = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnLoadBeli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FormPembelian.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCool2.setName("panelCool2"); // NOI18N
        panelCool2.setLayout(null);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        btnAdd.setFont(resourceMap.getFont("btnAdd.font")); // NOI18N
        btnAdd.setIcon(resourceMap.getIcon("btnAdd.icon")); // NOI18N
        btnAdd.setText(resourceMap.getString("btnAdd.text")); // NOI18N
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(10, 10, 80, 25);

        btnDeletePembelianAll.setFont(resourceMap.getFont("btnDeletePembelianAll.font")); // NOI18N
        btnDeletePembelianAll.setIcon(resourceMap.getIcon("btnDeletePembelianAll.icon")); // NOI18N
        btnDeletePembelianAll.setText(resourceMap.getString("btnDeletePembelianAll.text")); // NOI18N
        btnDeletePembelianAll.setName("btnDeletePembelianAll"); // NOI18N
        btnDeletePembelianAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePembelianAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletePembelianAll);
        btnDeletePembelianAll.setBounds(350, 10, 90, 25);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(564, 10, 60, 16);

        txtKriteria.setFont(resourceMap.getFont("txtKriteria.font")); // NOI18N
        txtKriteria.setName("txtKriteria"); // NOI18N
        txtKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKriteriaActionPerformed(evt);
            }
        });
        jPanel1.add(txtKriteria);
        txtKriteria.setBounds(760, 10, 200, 24);

        cbokriteria.setFont(resourceMap.getFont("cbokriteria.font")); // NOI18N
        cbokriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbokriteria.setName("cbokriteria"); // NOI18N
        cbokriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbokriteriaActionPerformed(evt);
            }
        });
        jPanel1.add(cbokriteria);
        cbokriteria.setBounds(620, 10, 130, 22);
        jPanel1.add(tglTransaksi);
        tglTransaksi.setBounds(780, 10, 180, 20);

        btnFilter.setFont(resourceMap.getFont("btnFilter.font")); // NOI18N
        btnFilter.setIcon(resourceMap.getIcon("btnFilter.icon")); // NOI18N
        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilter);
        btnFilter.setBounds(970, 10, 90, 25);

        cboStatus.setFont(resourceMap.getFont("cboStatus.font")); // NOI18N
        cboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboStatus.setName("cboStatus"); // NOI18N
        jPanel1.add(cboStatus);
        cboStatus.setBounds(780, 10, 180, 22);

        btnview.setFont(resourceMap.getFont("btnview.font")); // NOI18N
        btnview.setIcon(resourceMap.getIcon("btnview.icon")); // NOI18N
        btnview.setText(resourceMap.getString("btnview.text")); // NOI18N
        btnview.setName("btnview"); // NOI18N
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnview);
        btnview.setBounds(100, 10, 90, 25);

        btnBayarPenerimaanHutang.setFont(resourceMap.getFont("btnBayarPenerimaanHutang.font")); // NOI18N
        btnBayarPenerimaanHutang.setIcon(resourceMap.getIcon("btnBayarPenerimaanHutang.icon")); // NOI18N
        btnBayarPenerimaanHutang.setText(resourceMap.getString("btnBayarPenerimaanHutang.text")); // NOI18N
        btnBayarPenerimaanHutang.setName("btnBayarPenerimaanHutang"); // NOI18N
        btnBayarPenerimaanHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarPenerimaanHutangActionPerformed(evt);
            }
        });
        jPanel1.add(btnBayarPenerimaanHutang);
        btnBayarPenerimaanHutang.setBounds(200, 10, 140, 25);

        btnKeluar.setFont(resourceMap.getFont("btnKeluar.font")); // NOI18N
        btnKeluar.setIcon(resourceMap.getIcon("btnKeluar.icon")); // NOI18N
        btnKeluar.setText(resourceMap.getString("btnKeluar.text")); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar);
        btnKeluar.setBounds(1070, 10, 99, 25);

        btnLoadBeli.setFont(resourceMap.getFont("btnLoadBeli.font")); // NOI18N
        btnLoadBeli.setIcon(resourceMap.getIcon("btnLoadBeli.icon")); // NOI18N
        btnLoadBeli.setText(resourceMap.getString("btnLoadBeli.text")); // NOI18N
        btnLoadBeli.setName("btnLoadBeli"); // NOI18N
        btnLoadBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadBeliActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoadBeli);
        btnLoadBeli.setBounds(446, 10, 90, 25);

        panelCool2.add(jPanel1);
        jPanel1.setBounds(10, 10, 1180, 40);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        panelCool2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 870, 330);

        getContentPane().add(panelCool2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
// TODO add your handling code here:
//    DialogPembelian dp = new DialogPembelian(null, false);
//    dp.setVisible(true);

    DialogPembelianInternal p = new DialogPembelianInternal();
    p.toFront();
    JavarieSoftView.panelCool1.add(p);
    p.setVisible(true);
}//GEN-LAST:event_btnAddActionPerformed

private void cbokriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbokriteriaActionPerformed
// TODO add your handling code here:
    pilihKriteria(cbokriteria.getSelectedIndex());
}//GEN-LAST:event_cbokriteriaActionPerformed

private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
    try {
        // TODO add your handling code here:
        reloadData(c);
        //c.close();
    } catch (Exception ex) {
        Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_btnFilterActionPerformed

private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
// TODO add your handling code here:
//    try {
//        DialogPembelian d1 = new DialogPembelian(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()), Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString()), 0);
//        d1.setVisible(true);
//    } catch (Exception e) {
//    }

    DialogPembelianInternal p = new DialogPembelianInternal(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()), Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString()), 0);
    p.toFront();
    JavarieSoftView.panelCool1.add(p);
    p.setVisible(true);

}//GEN-LAST:event_btnviewActionPerformed

private void btnDeletePembelianAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePembelianAllActionPerformed
    //Connection c = null;
    try {
        //c = koneksi.getKoneksiJ();
        c.createStatement().execute("set autocommit false");
        int x = JOptionPane.showConfirmDialog(this, "Apakah Data Di Hapus?", "", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            // TODO add your handling code here:
////            if (!KontrolTanggalDao.cekHarian(c, jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString())) {
////                JOptionPane.showMessageDialog(null, "Transaksi Tidak Bisa Dilakukan Karena :\n"
////                        + "1.Transaksi Untuk Tanggal Ini Sudah Tutup atau\n"
////                        + "2.Transaksi Untuk Tanggal Ini Belum Dibuka");
////            } else {
                String tgal[] = Util.split(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString(), "-");
                String per = tgal[0] + "." + Integer.parseInt(tgal[1]);
                if (cekperiodeAda(c, per)) {
                    if (cekperiode(c, per)) {
                        aksilog = "Delete";
                        Statement sf = c.createStatement();
                        sf.execute("delete from PEMBELIAN where ID=" + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
                        String sql = "SELECT ID from HUTANG where IDPEMBELIAN ='" + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "'";
                        ResultSet rs = sf.executeQuery(sql);
                        if (rs.next()) {
                            if (rs.getInt(1) != 0) {
                                sf.executeUpdate("delete from HUTANGBAYAR where IDHUTANG='" + rs.getInt(1) + "'");
                            }
                        }
                        // sf.execute("delete from STOK where IDPENJUALAN="+ jTable1.getValueAt(jTable1.getSelectedRow(), 0) +" AND KODETRANS='B'");
                        prosesUpdateLog(c);
                        c.commit();
                        JOptionPane.showMessageDialog(this, "Delete Ok");
                        rs.close();
                        sf.close();
                        reloadData(c);
                    } else {
                        JOptionPane.showMessageDialog(null, "Transaksi Untuk Periode Ini Sudah Di Tutup.. !");
                        btnDeletePembelianAll.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Transaksi Untuk Periode Ini Belum Dibuka.. !");
                    btnDeletePembelianAll.requestFocus();
                }
////            }
        } else {
            System.out.print("tidak");
        }

    } catch (SQLException ex) {
        try {
            c.rollback();
            JOptionPane.showMessageDialog(this, "Rollback :" + ex.getMessage());
        } catch (SQLException ex1) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }
//    finally {
//        if(c!=null){
//            try {
//                c.createStatement().execute("set autocommit true");
//                c.close();
//            } catch (SQLException ex) {
//                Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//    }
}//GEN-LAST:event_btnDeletePembelianAllActionPerformed

private void btnBayarPenerimaanHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarPenerimaanHutangActionPerformed
// TODO add your handling code here:
    DialogHutang d1 = new DialogHutang(null, true, jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
    d1.setVisible(true);
}//GEN-LAST:event_btnBayarPenerimaanHutangActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnLoadBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadBeliActionPerformed
        // TODO add your handling code here:
//        try {
//            DialogPembelian d1 = new DialogPembelian(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()), Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString()), 1);
//            d1.setVisible(true);
//        } catch (Exception e) {
//        }

        DialogPembelianInternal p = new DialogPembelianInternal(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()), Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString()), 1);
        p.toFront();
        JavarieSoftView.panelCool1.add(p);
        p.setVisible(true);

    }//GEN-LAST:event_btnLoadBeliActionPerformed

    private void txtKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKriteriaActionPerformed
        // TODO add your handling code here:
        try {
        // TODO add your handling code here:
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            //c = koneksi.getKoneksiJ();
            reloadData(c);
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (Exception ex) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtKriteriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    public static javax.swing.JButton btnBayarPenerimaanHutang;
    public static javax.swing.JButton btnDeletePembelianAll;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnKeluar;
    public static javax.swing.JButton btnLoadBeli;
    public static javax.swing.JButton btnview;
    private javax.swing.JComboBox cboStatus;
    private javax.swing.JComboBox cbokriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private com.erv.function.PanelCool panelCool2;
    private datechooser.beans.DateChooserCombo tglTransaksi;
    private com.erv.function.TextFieldCool txtKriteria;
    // End of variables declaration//GEN-END:variables

    void pilihKriteria(int pil) {
        if (pil == 0) {
            tglTransaksi.setVisible(true);
            txtKriteria.setVisible(false);
            cboStatus.setVisible(false);
        } else if (pil == 1) {
            tglTransaksi.setVisible(false);
            txtKriteria.setVisible(true);
            cboStatus.setVisible(false);
        } else if (pil == 2) {
            tglTransaksi.setVisible(false);
            txtKriteria.setVisible(false);
            cboStatus.setVisible(true);
        } else if (pil == 3) {
            tglTransaksi.setVisible(false);
            txtKriteria.setVisible(true);
            cboStatus.setVisible(false);
        }

    }

    void reloadData(Connection c) {
        try {
            JDBCAdapter j = new JDBCAdapter(c);
            String sql = "select p.ID,p.NOFAKTUR,p.TANGGAL,s.NAMA,"
                    + "ifnull((SELECT case HUTANG.STATUS when '0' then 'LUNAS' when '1' then 'BELUM LUNAS' end FROM HUTANG WHERE  HUTANG.IDPEMBELIAN = p.ID),0) as STATUS,\n"
                    + "p.TGLBAYAR,\n"
                    + "ifnull((SELECT HUTANG.JUMLAH FROM HUTANG WHERE  HUTANG.IDPEMBELIAN = p.ID),0) as HUTANG,\n"
                    + "ifnull((SELECT sum(HUTANGBAYAR.JUMLAH)\n"
                    + "FROM HUTANG INNER JOIN HUTANGBAYAR ON HUTANG.ID = HUTANGBAYAR.IDHUTANG\n"
                    + "WHERE HUTANG.IDPEMBELIAN = p.ID),0) as BAYAR,\n"
                    + "ifnull((SELECT HUTANG.JUMLAH FROM HUTANG WHERE  HUTANG.IDPEMBELIAN = p.ID),0) - ifnull((SELECT sum(HUTANGBAYAR.JUMLAH)\n"
                    + "FROM HUTANG INNER JOIN HUTANGBAYAR ON HUTANG.ID = HUTANGBAYAR.IDHUTANG\n"
                    + "WHERE HUTANG.IDPEMBELIAN = p.ID),0) as SISA\n"
                    + "from PEMBELIAN p,SUPPLIER s where p.IDSUPPLIER=s.IDSUPPLIER ";
            if (cbokriteria.getSelectedIndex() == 0) {
                sql += " and p.TANGGAL='" + tglTransaksi.getText() + "'";
            }
            if (cbokriteria.getSelectedIndex() == 1) {
                sql += " and lower(s.NAMA) like '%" + txtKriteria.getText().toLowerCase() + "%'";
            }
            if (cbokriteria.getSelectedIndex() == 2) {
                if (cboStatus.getSelectedIndex() == 0) {
                    sql += " and p.STATUS ='0'";
                } else if (cboStatus.getSelectedIndex() == 1) {
                    sql += " and p.STATUS ='1'";
                }
            }
            if (cbokriteria.getSelectedIndex() == 3) {
                sql += " and p.NOFAKTUR like '%" + txtKriteria.getText() + "%'";
            }
            j.executeQuery(sql);
            jScrollPane1.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            TableColumn col = jTable1.getColumnModel().getColumn(0);
            col.setPreferredWidth(50);
            col = jTable1.getColumnModel().getColumn(1);
            col.setPreferredWidth(100);
            col = jTable1.getColumnModel().getColumn(2);
            col.setPreferredWidth(100);
            col = jTable1.getColumnModel().getColumn(3);
            col.setPreferredWidth(300);
            col = jTable1.getColumnModel().getColumn(4);
            col.setPreferredWidth(200);
            jTable1.setRowHeight(20);
            jTable1.setFont(new Font("Tahoma", Font.BOLD, 14));
            jScrollPane1.getViewport().add(jTable1);
            jScrollPane1.repaint();
            j.close();
        } catch (Exception ex) {
        }

    }

    private void setLayar() {
        jPanel1.setSize(dim.width - 40, 40);
        jScrollPane1.setLocation(jPanel1.getX(), jPanel1.getY() + jPanel1.getHeight() + 10);
        jScrollPane1.setSize(dim.width - 40, dim.height - 200);
    }

    private void isiCombo() {
        cbokriteria.removeAllItems();
        cboStatus.removeAllItems();
        cbokriteria.addItem("TANGGAL");
        cbokriteria.addItem("SUPPLIER");
        cbokriteria.addItem("STATUS");
        cbokriteria.addItem("NOFAKTUR");
        cboStatus.addItem("LUNAS");
        cboStatus.addItem("HUTANG");
    }

    void prosesUpdateLog(Connection c) {

        //java.sql.Date tanggallog;
        String tanggallog;
        String jamlog = u.jamsekarang + ":" + u.menitsekarang + ":" + u.detiksekarang;
        //tanggallog = java.sql.Date.valueOf(u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang);
        tanggallog = u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang;
        try {
            String ketlog = "";
            lh.setUSERIDENTITY(JavarieSoftApp.jenisuser);
            lh.setTANGGAL(tanggallog);
            lh.setJAM(jamlog);
            lh.setTABEL("TPEMBELIAN");
            lh.setNOREFF(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            lh.setAKSI(aksilog);
            if (aksilog.equals("Insert")) {
                ketlog = "Insert Data Pembelian " + jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            } else if (aksilog.equals("Update")) {
                ketlog = "Update Data Pembelian " + jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            } else if (aksilog.equals("Delete")) {
                ketlog = "Delete Data Pembelian No Faktur " + jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString() + " (" + jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString() + ") Pelanggan " + jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
            }
            lh.setKETERANGAN(ketlog);
            lhdao.insert(c, lh);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }

    public boolean cekperiode(Connection c, String periode) throws SQLException {
        //String periode = thn + "." + bln;
        boolean hasil1 = false;
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("select * from KONTROLPERIODE where PERIODE='" + periode + "' and STATUSSTOK='1'");

        if (rs.next()) {
            if (rs.getString(1) != null) {
                hasil1 = true;
            }
        }
        rs.close();
        s.close();
        return hasil1;
    }

    public boolean cekperiodeAda(Connection c, String bul) throws SQLException {
        //String periode = thn + "." + bln;
        boolean ada = false;
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery("select * from KONTROLPERIODE where PERIODE='" + bul + "'");

        if (rs.next()) {
            if (rs.getString(1) != null) {
                ada = true;
            }
        }
        rs.close();
        s.close();
        return ada;
    }
}
