/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormJenisBarang.java
 *
 * Created on Nov 14, 2011, 11:21:47 PM
 */
package javariesoft;

import com.erv.db.jenisbarangDao;
import com.erv.db.koneksi;
import com.erv.function.JDBCAdapter;
import com.erv.model.jenisbarang;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import com.eigher.db.loghistoryDao;
import com.eigher.model.loghistory;

/**
 *
 * @author erwadi
 */
public final class FormJenisBarang extends javax.swing.JInternalFrame {

    jenisbarang b = null;
    jenisbarangDao dbjenis = null;
    loghistory lh;
    loghistoryDao lhdao;
    com.erv.function.Util u = new com.erv.function.Util();
    String aksilog = "";

    /**
     * Creates new form FormJenisBarang
     */
    public FormJenisBarang() {
        initComponents();
        b = new jenisbarang();
        Connection c = null;
        try {
            c = koneksi.getKoneksiJ();
            lh = new loghistory();
            lhdao = new loghistoryDao();
            cektombol();
            reloadData(c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        } finally {
            if (c != null) {
                try {
                    c.close();
                } catch (SQLException ex) {
                    Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        dbjenis = new jenisbarangDao();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCool1 = new com.erv.function.PanelCool();
        jLabel1 = new javax.swing.JLabel();
        kodejenis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JTextField();
        cmdInsert = new javax.swing.JButton();
        cmdUpdate = new javax.swing.JButton();
        cmdDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtKriteria = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FormJenisBarang.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCool1.setName("panelCool1"); // NOI18N
        panelCool1.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelCool1.add(jLabel1);
        jLabel1.setBounds(30, 30, 130, 15);

        kodejenis.setEditable(false);
        kodejenis.setFont(resourceMap.getFont("kodejenis.font")); // NOI18N
        kodejenis.setText(resourceMap.getString("kodejenis.text")); // NOI18N
        kodejenis.setName("kodejenis"); // NOI18N
        panelCool1.add(kodejenis);
        kodejenis.setBounds(170, 60, 310, 21);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelCool1.add(jLabel2);
        jLabel2.setBounds(30, 60, 130, 16);

        jenis.setFont(resourceMap.getFont("jenis.font")); // NOI18N
        jenis.setText(resourceMap.getString("jenis.text")); // NOI18N
        jenis.setName("jenis"); // NOI18N
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jenis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jenisFocusLost(evt);
            }
        });
        jenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jenisKeyPressed(evt);
            }
        });
        panelCool1.add(jenis);
        jenis.setBounds(170, 30, 310, 21);

        cmdInsert.setFont(resourceMap.getFont("cmdInsert.font")); // NOI18N
        cmdInsert.setIcon(resourceMap.getIcon("cmdInsert.icon")); // NOI18N
        cmdInsert.setText(resourceMap.getString("cmdInsert.text")); // NOI18N
        cmdInsert.setName("cmdInsert"); // NOI18N
        cmdInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInsertActionPerformed(evt);
            }
        });
        panelCool1.add(cmdInsert);
        cmdInsert.setBounds(30, 100, 90, 25);

        cmdUpdate.setFont(resourceMap.getFont("cmdUpdate.font")); // NOI18N
        cmdUpdate.setIcon(resourceMap.getIcon("cmdUpdate.icon")); // NOI18N
        cmdUpdate.setText(resourceMap.getString("cmdUpdate.text")); // NOI18N
        cmdUpdate.setName("cmdUpdate"); // NOI18N
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });
        panelCool1.add(cmdUpdate);
        cmdUpdate.setBounds(125, 100, 97, 25);

        cmdDelete.setFont(resourceMap.getFont("cmdDelete.font")); // NOI18N
        cmdDelete.setIcon(resourceMap.getIcon("cmdDelete.icon")); // NOI18N
        cmdDelete.setText(resourceMap.getString("cmdDelete.text")); // NOI18N
        cmdDelete.setName("cmdDelete"); // NOI18N
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });
        panelCool1.add(cmdDelete);
        cmdDelete.setBounds(225, 100, 100, 25);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panelCool1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 560, 310);

        jSeparator1.setName("jSeparator1"); // NOI18N
        panelCool1.add(jSeparator1);
        jSeparator1.setBounds(10, 90, 550, 10);

        jSeparator2.setName("jSeparator2"); // NOI18N
        panelCool1.add(jSeparator2);
        jSeparator2.setBounds(10, 130, 550, 10);

        btnCancel.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnCancel.setIcon(resourceMap.getIcon("btnCancel.icon")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelCool1.add(btnCancel);
        btnCancel.setBounds(350, 100, 100, 25);

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jLabel7.foreground")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        panelCool1.add(jLabel7);
        jLabel7.setBounds(30, 140, 150, 16);

        txtKriteria.setFont(resourceMap.getFont("txtKriteria.font")); // NOI18N
        txtKriteria.setName("txtKriteria"); // NOI18N
        txtKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKriteriaActionPerformed(evt);
            }
        });
        panelCool1.add(txtKriteria);
        txtKriteria.setBounds(170, 140, 220, 22);

        btnFilter.setFont(resourceMap.getFont("btnFilter.font")); // NOI18N
        btnFilter.setIcon(resourceMap.getIcon("btnFilter.icon")); // NOI18N
        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        panelCool1.add(btnFilter);
        btnFilter.setBounds(410, 140, 100, 25);

        btnKeluar.setFont(resourceMap.getFont("btnKeluar.font")); // NOI18N
        btnKeluar.setIcon(resourceMap.getIcon("btnKeluar.icon")); // NOI18N
        btnKeluar.setText(resourceMap.getString("btnKeluar.text")); // NOI18N
        btnKeluar.setName("btnKeluar"); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        panelCool1.add(btnKeluar);
        btnKeluar.setBounds(455, 100, 100, 25);

        getContentPane().add(panelCool1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 591, 515);
    }// </editor-fold>//GEN-END:initComponents

private void cmdInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInsertActionPerformed
// TODO add your handling code here:
    Connection c = null;
    int x = JOptionPane.showConfirmDialog(this, "Apakah Data Akan Disimpan?", "", JOptionPane.YES_NO_OPTION);
    if (x == 0) {
        if ((jenis.getText().equals("")) || (kodejenis.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap.. !");
            jenis.requestFocus();
        } else {
            try {
                aksilog = "Insert";
                c = koneksi.getKoneksiJ();
                c.createStatement().execute("set autocommit false");
                prosesUpdate(c, 0);
                prosesUpdateLog(c);
                reloadData(c);
                cektombol();
                kosong();
                c.commit();
                jenis.requestFocus();
            } catch (SQLException ex) {
                Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (c != null) {
                    try {
                        c.createStatement().execute("set autocommit true");
                        c.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    } else {
        jenis.requestFocus();
    }
}//GEN-LAST:event_cmdInsertActionPerformed

private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
// TODO add your handling code here:
    Connection c = null;
    int x = JOptionPane.showConfirmDialog(this, "Apakah Data Akan Diedit?", "", JOptionPane.YES_NO_OPTION);
    if (x == 0) {
        if ((jenis.getText().equals("")) || (kodejenis.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Data Belum Lengkap.. !");
            jenis.requestFocus();
        } else {
            try {
                aksilog = "Update";
                c = koneksi.getKoneksiJ();
                c.createStatement().execute("set autocommit false");
                prosesUpdate(c, 1);
                prosesUpdateLog(c);
                reloadData(c);
                cektombol();
                kosong();
                jenis.requestFocus();
                c.commit();
            } catch (SQLException ex) {
                Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (c != null) {
                    try {
                        c.createStatement().execute("set autocommit true");
                        c.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    } else {
        jenis.requestFocus();
    }
}//GEN-LAST:event_cmdUpdateActionPerformed

private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
    Connection c = null;
    try {
        c = koneksi.getKoneksiJ();
        c.createStatement().execute("set autocommit false");
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Apakah Data Akan Dihapus?", "", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            aksilog = "Delete";
            jenisbarangDao.deleteFromJENISBARANG(c, kodejenis.getText());
            prosesUpdateLog(c);
            reloadData(c);
            cektombol();
            kosong();
            jenis.requestFocus();
            c.commit();
        } else {
            jenis.requestFocus();
        }
    } catch (SQLException ex) {
        Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        if (c != null) {
            try {
                c.createStatement().execute("set autocommit true");
                c.close();
            } catch (SQLException ex) {
                Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}//GEN-LAST:event_cmdDeleteActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    try {
        // TODO add your handling code here: 
        Connection c = koneksi.getKoneksiJ();
        b = jenisbarangDao.getDetails(c, jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        kodejenis.setText(b.getID());
        jenis.setText(b.getJENIS());
        cektombol();
        c.close();
    } catch (SQLException ex) {
        Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
    }

}//GEN-LAST:event_jTable1MouseClicked

private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
    try {
        // TODO add your handling code here:
        Connection c = koneksi.getKoneksiJ();
        jenis.setText(jenis.getText().toUpperCase());
        kodejenis.setText(jenisbarangDao.getID(c) + "");
        cmdInsert.requestFocus();
        c.close();
    } catch (SQLException ex) {
        Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_jenisActionPerformed

private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
// TODO add your handling code here:
    kosong();
    cektombol();
    jenis.requestFocus();
}//GEN-LAST:event_btnCancelActionPerformed

private void jenisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jenisFocusLost
// TODO add your handling code here:
    cmdInsert.requestFocus();
}//GEN-LAST:event_jenisFocusLost

private void jenisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenisKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == 10) {
        cmdInsert.requestFocus();
    }
}//GEN-LAST:event_jenisKeyPressed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        try {
            // TODO add your handling code here:
            Connection c = koneksi.getKoneksiJ();
            reloadData(c);
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void txtKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKriteriaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection c = koneksi.getKoneksiJ();
            reloadData(c);
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormJenisBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtKriteriaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdInsert;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField kodejenis;
    private com.erv.function.PanelCool panelCool1;
    private javax.swing.JTextField txtKriteria;
    // End of variables declaration//GEN-END:variables

    void kosong() {
        kodejenis.setText("");
        jenis.setText("");
    }

    void prosesUpdate(Connection c, int p) {
        b.setID(kodejenis.getText());
        b.setJENIS(jenis.getText());
        try {
            boolean stat;
            if (p == 0) {
                stat = jenisbarangDao.insertIntoJENISBARANG(c, b);
            } else {
                stat = jenisbarangDao.updateJENISBARANG(c, b.getID(), b);
            }
            if (stat) {
                JOptionPane.showMessageDialog(this, "Update Data Ok");
            } else {
                JOptionPane.showMessageDialog(this, "Update Data Gagal");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }

    public void reloadData(Connection c) {
        try {
            JDBCAdapter j = new JDBCAdapter(c);
            String sql = "select * from JENISBARANG where lower(ID) like '"
                    + txtKriteria.getText().toLowerCase() + "%' OR lower(JENIS) like '%"
                    + txtKriteria.getText().toLowerCase() + "%' ORDER BY JENIS";
            j.executeQuery(sql);
            jScrollPane1.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jScrollPane1.getViewport().add(jTable1);
            jScrollPane1.repaint();
        } catch (Exception ex) {
            Logger.getLogger(FormBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void settingtombol(boolean simp, boolean edit, boolean hapus) {
        cmdInsert.setEnabled(simp);
        cmdUpdate.setEnabled(edit);
        cmdDelete.setEnabled(hapus);
    }

    void prosesUpdateLog(Connection c) {
        //java.sql.Date tanggallog;
        String tanggallog;
        String jamlog = u.jamsekarang + ":" + u.menitsekarang + ":" + u.detiksekarang;
        //tanggallog = java.sql.Date.valueOf(u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang);
        tanggallog = u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang;
        try {
            String ketlog = "";
            lh.setUSERIDENTITY(JavarieSoftApp.jenisuser);
            lh.setTANGGAL(tanggallog);
            lh.setJAM(jamlog);
            lh.setTABEL("TJENISBARANG");
            lh.setNOREFF(kodejenis.getText());
            lh.setAKSI(aksilog);
            if (aksilog.equals("Insert")) {
                ketlog = "Insert Data Merk " + kodejenis.getText();
            } else if (aksilog.equals("Update")) {
                ketlog = "Update Data Merk " + kodejenis.getText();
            } else if (aksilog.equals("Delete")) {
                ketlog = "Delete Data Merk " + kodejenis.getText();
            }
            lh.setKETERANGAN(ketlog);
            lhdao.insert(c, lh);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }

    void cektombol() {
        if (JavarieSoftApp.groupuser.equals("Pembelian")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Penjualan")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Administrator")) {
            settingtombol(true, true, false);
        } else if (JavarieSoftApp.groupuser.equals("KaGudang")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Operator")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Accounting")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Asisten Administrator")) {
            settingtombol(true, true, false);
        } else if (JavarieSoftApp.groupuser.equals("Master Data")) {
            settingtombol(true, false, false);
        }
    }
}
