/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javariesoft;

import com.erv.controller.NomorPajakController;
import com.erv.db.koneksi;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class FormNomorpajak extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormNomorpajak
     */
    Connection con;
    NomorPajakController controller;
    public FormNomorpajak() {
        try {
            initComponents();
            con = koneksi.getKoneksiJ();
            controller = new NomorPajakController(this);
            controller.clearForm();
            controller.reloadData(con);
        } catch (SQLException ex) {
            Logger.getLogger(FormNomorpajak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JTextField getTxtNomorakhir() {
        return txtNomorakhir;
    }

    public void setTxtNomorakhir(JTextField txtNomorakhir) {
        this.txtNomorakhir = txtNomorakhir;
    }

    public JTextField getTxtNomorakhirpakai() {
        return txtNomorakhirpakai;
    }

    public void setTxtNomorakhirpakai(JTextField txtNomorakhirpakai) {
        this.txtNomorakhirpakai = txtNomorakhirpakai;
    }

    public JTextField getTxtNomorawal() {
        return txtNomorawal;
    }

    public void setTxtNomorawal(JTextField txtNomorawal) {
        this.txtNomorawal = txtNomorawal;
    }

    public JTable getTabelNomorPajak() {
        return tabelNomorPajak;
    }

    public void setTabelNomorPajak(JTable tabelNomorPajak) {
        this.tabelNomorPajak = tabelNomorPajak;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCool1 = new com.erv.function.PanelCool();
        jLabel1 = new javax.swing.JLabel();
        txtNomorawal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomorakhir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomorakhirpakai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNomorPajak = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(FormNomorpajak.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCool1.setName("panelCool1"); // NOI18N
        panelCool1.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        panelCool1.add(jLabel1);
        jLabel1.setBounds(20, 20, 120, 15);

        txtNomorawal.setText(resourceMap.getString("txtNomorawal.text")); // NOI18N
        txtNomorawal.setName("txtNomorawal"); // NOI18N
        panelCool1.add(txtNomorawal);
        txtNomorawal.setBounds(170, 20, 190, 20);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelCool1.add(jLabel2);
        jLabel2.setBounds(20, 50, 130, 15);

        txtNomorakhir.setText(resourceMap.getString("txtNomorakhir.text")); // NOI18N
        txtNomorakhir.setName("txtNomorakhir"); // NOI18N
        panelCool1.add(txtNomorakhir);
        txtNomorakhir.setBounds(170, 50, 190, 20);

        jLabel3.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        panelCool1.add(jLabel3);
        jLabel3.setBounds(20, 80, 140, 15);

        txtNomorakhirpakai.setText(resourceMap.getString("txtNomorakhirpakai.text")); // NOI18N
        txtNomorakhirpakai.setName("txtNomorakhirpakai"); // NOI18N
        panelCool1.add(txtNomorakhirpakai);
        txtNomorakhirpakai.setBounds(170, 80, 190, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabelNomorPajak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelNomorPajak.setName("tabelNomorPajak"); // NOI18N
        tabelNomorPajak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNomorPajakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNomorPajak);

        panelCool1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 540, 210);

        btnInsert.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnInsert.setText(resourceMap.getString("btnInsert.text")); // NOI18N
        btnInsert.setName("btnInsert"); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        panelCool1.add(btnInsert);
        btnInsert.setBounds(20, 120, 100, 23);

        btnUpdate.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnUpdate.setText(resourceMap.getString("btnUpdate.text")); // NOI18N
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelCool1.add(btnUpdate);
        btnUpdate.setBounds(130, 120, 100, 23);

        btnDelete.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnDelete.setText(resourceMap.getString("btnDelete.text")); // NOI18N
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelCool1.add(btnDelete);
        btnDelete.setBounds(240, 120, 100, 23);

        btnCancel.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelCool1.add(btnCancel);
        btnCancel.setBounds(350, 120, 100, 23);

        btnExit.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelCool1.add(btnExit);
        btnExit.setBounds(460, 120, 100, 23);

        getContentPane().add(panelCool1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 599, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.insert(con); 
        controller.reloadData(con); 
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete(con);
        controller.reloadData(con); 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.update(con);
        controller.reloadData(con); 
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        controller.clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        try {
            // TODO add your handling code here:
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormNomorpajak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void tabelNomorPajakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelNomorPajakMouseClicked
        // TODO add your handling code here:
        controller.getNomorPajak(con, Integer.parseInt(tabelNomorPajak.getValueAt(tabelNomorPajak.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_tabelNomorPajakMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.erv.function.PanelCool panelCool1;
    private javax.swing.JTable tabelNomorPajak;
    private javax.swing.JTextField txtNomorakhir;
    private javax.swing.JTextField txtNomorakhirpakai;
    private javax.swing.JTextField txtNomorawal;
    // End of variables declaration//GEN-END:variables
}
