/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javariesoft;

import com.erv.db.KontrolTanggalDao;
import com.erv.db.KontrolperiodeDao;
import com.erv.db.koneksi;
import com.erv.function.Util;
import com.erv.model.Kontroltanggal;
import com.erv.model.TableKontrolTanggalModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author TI-PNP
 */
public class FormKontrolTanggal extends javax.swing.JInternalFrame implements ListSelectionListener {

    /**
     * Creates new form FormKontrolTanggal
     */
    private int id;
    private TableKontrolTanggalModel tableKontrolTanggalModel;
    private SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    private Kontroltanggal kontroltanggal = null;
    Connection c;

    public FormKontrolTanggal() {
        tableKontrolTanggalModel = new TableKontrolTanggalModel();
        kontroltanggal = new Kontroltanggal();
        initComponents();
        try {
            c = koneksi.getKoneksiJ();
        } catch (SQLException ex) {
            Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.getSelectionModel().addListSelectionListener(this);
        tabel.setModel(tableKontrolTanggalModel);
        dcTanggal.setDateFormat(df);
        Util util = new Util();
        txttahun.setText("" + util.thnsekarang);
        cbobulan.setSelectedIndex(util.blnsekarang - 1);
        loadData();
        cektombol();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dcTanggal = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbobulan = new javax.swing.JComboBox();
        txttahun = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FormKontrolTanggal.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 17, 116, 15);

        dcTanggal.setFieldFont(resourceMap.getFont("dcTanggal.dch_combo_fieldFont")); // NOI18N
        jPanel1.add(dcTanggal);
        dcTanggal.setBounds(136, 11, 155, 20);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 116, 15);

        cboStatus.setFont(resourceMap.getFont("cboStatus.font")); // NOI18N
        cboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buka", "Tutup" }));
        cboStatus.setName("cboStatus"); // NOI18N
        jPanel1.add(cboStatus);
        cboStatus.setBounds(136, 37, 155, 21);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        btnInsert.setFont(resourceMap.getFont("btnEdit.font")); // NOI18N
        btnInsert.setText(resourceMap.getString("btnInsert.text")); // NOI18N
        btnInsert.setName("btnInsert"); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert);
        btnInsert.setBounds(10, 10, 140, 30);

        btnUpdate.setFont(resourceMap.getFont("btnUpdate.font")); // NOI18N
        btnUpdate.setText(resourceMap.getString("btnUpdate.text")); // NOI18N
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(160, 10, 140, 30);

        btnDelete.setFont(resourceMap.getFont("btnEdit.font")); // NOI18N
        btnDelete.setText(resourceMap.getString("btnDelete.text")); // NOI18N
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);
        btnDelete.setBounds(310, 10, 140, 30);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setName("tabel"); // NOI18N
        jScrollPane1.setViewportView(tabel);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(null);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 8, 60, 20);

        cbobulan.setFont(resourceMap.getFont("cbobulan.font")); // NOI18N
        cbobulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbobulan.setName("cbobulan"); // NOI18N
        jPanel3.add(cbobulan);
        cbobulan.setBounds(97, 8, 90, 21);

        txttahun.setFont(resourceMap.getFont("txttahun.font")); // NOI18N
        txttahun.setText(resourceMap.getString("txttahun.text")); // NOI18N
        txttahun.setName("txttahun"); // NOI18N
        txttahun.setPreferredSize(new java.awt.Dimension(150, 26));
        jPanel3.add(txttahun);
        txttahun.setBounds(192, 5, 150, 26);

        btnFilter.setFont(resourceMap.getFont("btnFilter.font")); // NOI18N
        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jPanel3.add(btnFilter);
        btnFilter.setBounds(347, 4, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 671, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            // TODO add your handling code here:
            c.createStatement().execute("set autocommit false");
            kontroltanggal.setId(0);
            kontroltanggal.setTanggal(dcTanggal.getText());
            kontroltanggal.setStatus(cboStatus.getSelectedIndex());

            KontrolTanggalDao.insertIntoKONTROLTANGGAL(c, kontroltanggal);
            c.commit();
            tableKontrolTanggalModel.add(kontroltanggal);
            cektombol();
            JOptionPane.showMessageDialog(this, "Entri Data Ok");
        } catch (SQLException ex) {
            try {
                c.rollback();
                JOptionPane.showMessageDialog(this, "Rollback " + ex.getMessage());
            } catch (SQLException ex1) {
                Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } finally {
            try {
                c.createStatement().execute("set autocommit true");
            } catch (SQLException ex) {
                Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            c.createStatement().execute("set autocommit false");
            kontroltanggal.setId(getId());
            kontroltanggal.setTanggal(dcTanggal.getText());
            kontroltanggal.setStatus(cboStatus.getSelectedIndex());

            KontrolTanggalDao.updateKONTROLTANGGAL(c, kontroltanggal);
            c.commit();
            tableKontrolTanggalModel.set(tabel.getSelectedRow(), kontroltanggal);
            cektombol();
            JOptionPane.showMessageDialog(this, "Edit Data Ok");
        } catch (SQLException ex) {
            try {
                c.rollback();
                JOptionPane.showMessageDialog(this, "Rollback " + ex.getMessage());
            } catch (SQLException ex1) {
                Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } finally {
            try {
                c.createStatement().execute("set autocommit true");
            } catch (SQLException ex) {
                Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            c.createStatement().execute("set autocommit false");
            KontrolTanggalDao.deleteFromKONTROLTANGGAL(c, getId());
            c.commit();
            tableKontrolTanggalModel.remove(tabel.getSelectedRow());
            cektombol();
            JOptionPane.showMessageDialog(this, "Delete Data Ok");
        } catch (SQLException ex) {
            try {
                c.rollback();
                JOptionPane.showMessageDialog(this, "Rollback " + ex.getMessage());
            } catch (SQLException ex1) {
                Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex1);
            }
        } finally {
            try {
                c.createStatement().execute("set autocommit true");
            } catch (SQLException ex) {
                Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cboStatus;
    private javax.swing.JComboBox cbobulan;
    private datechooser.beans.DateChooserCombo dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables

    public void valueChanged(ListSelectionEvent e) {
        try {
            Calendar cld = Calendar.getInstance();
            Kontroltanggal k = tableKontrolTanggalModel.get(tabel.getSelectedRow());
            setId(k.getId());
            cld.setTime(df.parse(k.getTanggal()));
            dcTanggal.setSelectedDate(cld);
            cboStatus.setSelectedIndex(k.getStatus());
        } catch (IndexOutOfBoundsException ex) {

        } catch (ParseException ex) {
            Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadData() {
        try {
            List<Kontroltanggal> list = KontrolTanggalDao.getKontroltanggals(c, cbobulan.getSelectedIndex() + 1, Integer.parseInt(txttahun.getText()));
            tableKontrolTanggalModel.setList(list);
            tabel.revalidate();
            jScrollPane1.repaint();
        } catch (SQLException ex) {
            Logger.getLogger(FormKontrolTanggal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void settingtombol(boolean simp, boolean edit, boolean hapus) {
        btnInsert.setEnabled(simp);
        btnUpdate.setEnabled(edit);
        btnDelete.setEnabled(hapus);
    }

    void cektombol() {
        if (JavarieSoftApp.groupuser.equals("Pembelian")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Penjualan")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Administrator")) {
            settingtombol(true, true, false);
        } else if (JavarieSoftApp.groupuser.equals("KaGudang")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Operator")) {
            settingtombol(false, false, false);
        } else if (JavarieSoftApp.groupuser.equals("Accounting")) {
            settingtombol(false, false, false);
        }
    }
}
