/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Medisia.java
 *
 * Created on Mar 23, 2013, 12:08:03 PM
 */
package javariesoft;

import com.erv.db.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ervan Asri
 */
public class Zaren extends javax.swing.JApplet {

    public static String BASE = "";
    public static String IP = "";
    public static String IPDB = "";
    Connection con=null;
    /** Initializes the applet Medisia */
    @Override
    public void init() {
        //Medisia g = new Medisia()
        IP = getCodeBase().getHost();
        IPDB = getParameter("IPDB");
        BASE = getCodeBase().toString();
        //global.URL = BASE;
        //global.REPORT = BASE + "report";
        global.REPORT=getParameter("IPREPORT");
        //global.REPORT="file:/D:/PROJECT/MANPRO JAVARIESOFT/DEAN BOUTIQUE/Program/DeanSoft/report";
        koneksi.IP = IPDB;
        //JOptionPane.showMessageDialog(null, global.REPORT);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//
//            }
//            //JOptionPane.showMessageDialog(null, msg);
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Medisia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Medisia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Medisia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Medisia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                    //nonaktif();
                    aktif();
                    konek();
                }
            });
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    @Override
    public void destroy() {
        try {
            con=null;
        } catch (Exception ex) {
            Logger.getLogger(Zaren.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCool1 = new com.erv.model.DesktopCool();
        LblJenis = new javax.swing.JLabel();
        LblJenis1 = new javax.swing.JLabel();
        LblJenis2 = new javax.swing.JLabel();
        LblJenis3 = new javax.swing.JLabel();
        LblJenis4 = new javax.swing.JLabel();
        Lblgroup = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Mlogin = new javax.swing.JMenu();
        Mloginuser = new javax.swing.JMenuItem();
        MlogOf = new javax.swing.JMenuItem();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        MuserAccount = new javax.swing.JMenuItem();
        MeditPassword = new javax.swing.JMenuItem();
        MaktivaTetap = new javax.swing.JMenuItem();
        Mperkiraan = new javax.swing.JMenuItem();
        Mbarang = new javax.swing.JMenu();
        MMerkBarang = new javax.swing.JMenuItem();
        MkategoriBrg = new javax.swing.JMenuItem();
        MdataBarang = new javax.swing.JMenuItem();
        Mpelanggan = new javax.swing.JMenuItem();
        Msupplier = new javax.swing.JMenuItem();
        Msales = new javax.swing.JMenuItem();
        Mbank = new javax.swing.JMenuItem();
        Msetting = new javax.swing.JMenuItem();
        MsettingStatPeriode = new javax.swing.JMenuItem();
        MlogHistory = new javax.swing.JMenuItem();
        Manalisa = new javax.swing.JMenu();
        Manalisastokbrg = new javax.swing.JMenuItem();
        MSearchingBarang = new javax.swing.JMenuItem();
        Mtransaksi = new javax.swing.JMenu();
        Mjurnal = new javax.swing.JMenuItem();
        MdeliveryOrder = new javax.swing.JMenuItem();
        Mpenjualan = new javax.swing.JMenuItem();
        Mpembelian = new javax.swing.JMenuItem();
        Mhutang = new javax.swing.JMenuItem();
        Mpiutang = new javax.swing.JMenuItem();
        Mtutupbuku = new javax.swing.JMenuItem();
        Mtutupstok = new javax.swing.JMenuItem();
        MkoreksiStok = new javax.swing.JMenuItem();
        Mlaporan = new javax.swing.JMenu();
        Mlappembelian = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        Mreturpembelian = new javax.swing.JMenu();
        Mreturbelifaktur = new javax.swing.JMenuItem();
        Mrekapreturbeli = new javax.swing.JMenuItem();
        MlapPenjualan = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        Mreturpenjualan = new javax.swing.JMenu();
        Mreturjualfaktur = new javax.swing.JMenuItem();
        Mrekapreturjual = new javax.swing.JMenuItem();
        Mlapdeliveryorder = new javax.swing.JMenu();
        MlapFakturDO = new javax.swing.JMenuItem();
        MrekapDO = new javax.swing.JMenuItem();
        MlapBarang = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        MlapHutang = new javax.swing.JMenu();
        MlapUmurHutang = new javax.swing.JMenuItem();
        MlapPiutang = new javax.swing.JMenu();
        MlapUmurPiutang = new javax.swing.JMenuItem();
        MlapUmurPiutangPersales = new javax.swing.JMenuItem();
        MLapPerkiraan = new javax.swing.JMenuItem();
        MlapFakturPajak = new javax.swing.JMenuItem();
        MlapTutupBuku = new javax.swing.JMenuItem();
        MlapJurnal = new javax.swing.JMenuItem();
        MlapBukuBesar = new javax.swing.JMenuItem();
        MlapNeraca = new javax.swing.JMenuItem();
        MlapRugiLaba = new javax.swing.JMenuItem();
        MlapEkuitas = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        Mkeluar = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();

        setName("Form"); // NOI18N

        panelCool1.setName("panelCool1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(Zaren.class);
        LblJenis.setFont(resourceMap.getFont("LblJenis.font")); // NOI18N
        LblJenis.setForeground(resourceMap.getColor("LblJenis.foreground")); // NOI18N
        LblJenis.setText(resourceMap.getString("LblJenis.text")); // NOI18N
        LblJenis.setName("LblJenis"); // NOI18N
        panelCool1.add(LblJenis);
        LblJenis.setBounds(120, 0, 200, 20);

        LblJenis1.setFont(resourceMap.getFont("LblJenis1.font")); // NOI18N
        LblJenis1.setForeground(resourceMap.getColor("LblJenis1.foreground")); // NOI18N
        LblJenis1.setText(resourceMap.getString("LblJenis1.text")); // NOI18N
        LblJenis1.setName("LblJenis1"); // NOI18N
        panelCool1.add(LblJenis1);
        LblJenis1.setBounds(100, 0, 10, 20);

        LblJenis2.setFont(resourceMap.getFont("LblJenis2.font")); // NOI18N
        LblJenis2.setForeground(resourceMap.getColor("LblJenis2.foreground")); // NOI18N
        LblJenis2.setText(resourceMap.getString("LblJenis2.text")); // NOI18N
        LblJenis2.setName("LblJenis2"); // NOI18N
        panelCool1.add(LblJenis2);
        LblJenis2.setBounds(10, 0, 80, 20);

        LblJenis3.setFont(resourceMap.getFont("LblJenis3.font")); // NOI18N
        LblJenis3.setForeground(resourceMap.getColor("LblJenis3.foreground")); // NOI18N
        LblJenis3.setText(resourceMap.getString("LblJenis3.text")); // NOI18N
        LblJenis3.setName("LblJenis3"); // NOI18N
        panelCool1.add(LblJenis3);
        LblJenis3.setBounds(10, 20, 80, 20);

        LblJenis4.setFont(resourceMap.getFont("LblJenis4.font")); // NOI18N
        LblJenis4.setForeground(resourceMap.getColor("LblJenis4.foreground")); // NOI18N
        LblJenis4.setText(resourceMap.getString("LblJenis4.text")); // NOI18N
        LblJenis4.setName("LblJenis4"); // NOI18N
        panelCool1.add(LblJenis4);
        LblJenis4.setBounds(100, 20, 10, 20);

        Lblgroup.setFont(resourceMap.getFont("Lblgroup.font")); // NOI18N
        Lblgroup.setForeground(resourceMap.getColor("Lblgroup.foreground")); // NOI18N
        Lblgroup.setText(resourceMap.getString("Lblgroup.text")); // NOI18N
        Lblgroup.setName("Lblgroup"); // NOI18N
        panelCool1.add(Lblgroup);
        Lblgroup.setBounds(120, 20, 200, 20);

        getContentPane().add(panelCool1, java.awt.BorderLayout.CENTER);

        menuBar.setName("menuBar"); // NOI18N

        Mlogin.setIcon(resourceMap.getIcon("Mlogin.icon")); // NOI18N
        Mlogin.setText(resourceMap.getString("Mlogin.text")); // NOI18N
        Mlogin.setName("Mlogin"); // NOI18N

        Mloginuser.setIcon(resourceMap.getIcon("Mloginuser.icon")); // NOI18N
        Mloginuser.setText(resourceMap.getString("Mloginuser.text")); // NOI18N
        Mloginuser.setName("Mloginuser"); // NOI18N
        Mloginuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MloginuserActionPerformed(evt);
            }
        });
        Mlogin.add(Mloginuser);

        MlogOf.setIcon(resourceMap.getIcon("MlogOf.icon")); // NOI18N
        MlogOf.setText(resourceMap.getString("MlogOf.text")); // NOI18N
        MlogOf.setName("MlogOf"); // NOI18N
        MlogOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlogOfActionPerformed(evt);
            }
        });
        Mlogin.add(MlogOf);

        menuBar.add(Mlogin);

        fileMenu.setIcon(resourceMap.getIcon("fileMenu.icon")); // NOI18N
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        MuserAccount.setIcon(resourceMap.getIcon("MuserAccount.icon")); // NOI18N
        MuserAccount.setText(resourceMap.getString("MuserAccount.text")); // NOI18N
        MuserAccount.setName("MuserAccount"); // NOI18N
        MuserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MuserAccountActionPerformed(evt);
            }
        });
        fileMenu.add(MuserAccount);

        MeditPassword.setIcon(resourceMap.getIcon("MeditPassword.icon")); // NOI18N
        MeditPassword.setText(resourceMap.getString("MeditPassword.text")); // NOI18N
        MeditPassword.setName("MeditPassword"); // NOI18N
        MeditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeditPasswordActionPerformed(evt);
            }
        });
        fileMenu.add(MeditPassword);

        MaktivaTetap.setIcon(resourceMap.getIcon("MaktivaTetap.icon")); // NOI18N
        MaktivaTetap.setText(resourceMap.getString("MaktivaTetap.text")); // NOI18N
        MaktivaTetap.setName("MaktivaTetap"); // NOI18N
        MaktivaTetap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaktivaTetapActionPerformed(evt);
            }
        });
        fileMenu.add(MaktivaTetap);

        Mperkiraan.setIcon(resourceMap.getIcon("Mperkiraan.icon")); // NOI18N
        Mperkiraan.setText(resourceMap.getString("Mperkiraan.text")); // NOI18N
        Mperkiraan.setName("Mperkiraan"); // NOI18N
        Mperkiraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MperkiraanActionPerformed(evt);
            }
        });
        fileMenu.add(Mperkiraan);

        Mbarang.setIcon(resourceMap.getIcon("Mbarang.icon")); // NOI18N
        Mbarang.setText(resourceMap.getString("Mbarang.text")); // NOI18N
        Mbarang.setName("Mbarang"); // NOI18N

        MMerkBarang.setIcon(resourceMap.getIcon("MMerkBarang.icon")); // NOI18N
        MMerkBarang.setText(resourceMap.getString("MMerkBarang.text")); // NOI18N
        MMerkBarang.setName("MMerkBarang"); // NOI18N
        MMerkBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMerkBarangActionPerformed(evt);
            }
        });
        Mbarang.add(MMerkBarang);

        MkategoriBrg.setIcon(resourceMap.getIcon("MkategoriBrg.icon")); // NOI18N
        MkategoriBrg.setText(resourceMap.getString("MkategoriBrg.text")); // NOI18N
        MkategoriBrg.setName("MkategoriBrg"); // NOI18N
        MkategoriBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MkategoriBrgActionPerformed(evt);
            }
        });
        Mbarang.add(MkategoriBrg);

        MdataBarang.setIcon(resourceMap.getIcon("MdataBarang.icon")); // NOI18N
        MdataBarang.setText(resourceMap.getString("MdataBarang.text")); // NOI18N
        MdataBarang.setName("MdataBarang"); // NOI18N
        MdataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MdataBarangActionPerformed(evt);
            }
        });
        Mbarang.add(MdataBarang);

        fileMenu.add(Mbarang);

        Mpelanggan.setIcon(resourceMap.getIcon("Mpelanggan.icon")); // NOI18N
        Mpelanggan.setText(resourceMap.getString("Mpelanggan.text")); // NOI18N
        Mpelanggan.setName("Mpelanggan"); // NOI18N
        Mpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpelangganActionPerformed(evt);
            }
        });
        fileMenu.add(Mpelanggan);

        Msupplier.setIcon(resourceMap.getIcon("Msupplier.icon")); // NOI18N
        Msupplier.setText(resourceMap.getString("Msupplier.text")); // NOI18N
        Msupplier.setName("Msupplier"); // NOI18N
        Msupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsupplierActionPerformed(evt);
            }
        });
        fileMenu.add(Msupplier);

        Msales.setIcon(resourceMap.getIcon("Msales.icon")); // NOI18N
        Msales.setText(resourceMap.getString("Msales.text")); // NOI18N
        Msales.setName("Msales"); // NOI18N
        Msales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsalesActionPerformed(evt);
            }
        });
        fileMenu.add(Msales);

        Mbank.setIcon(resourceMap.getIcon("Mbank.icon")); // NOI18N
        Mbank.setText(resourceMap.getString("Mbank.text")); // NOI18N
        Mbank.setName("Mbank"); // NOI18N
        Mbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbankActionPerformed(evt);
            }
        });
        fileMenu.add(Mbank);

        Msetting.setIcon(resourceMap.getIcon("Msetting.icon")); // NOI18N
        Msetting.setText(resourceMap.getString("Msetting.text")); // NOI18N
        Msetting.setName("Msetting"); // NOI18N
        Msetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsettingActionPerformed(evt);
            }
        });
        fileMenu.add(Msetting);

        MsettingStatPeriode.setIcon(resourceMap.getIcon("MsettingStatPeriode.icon")); // NOI18N
        MsettingStatPeriode.setText(resourceMap.getString("MsettingStatPeriode.text")); // NOI18N
        MsettingStatPeriode.setName("MsettingStatPeriode"); // NOI18N
        MsettingStatPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsettingStatPeriodeActionPerformed(evt);
            }
        });
        fileMenu.add(MsettingStatPeriode);

        MlogHistory.setIcon(resourceMap.getIcon("MlogHistory.icon")); // NOI18N
        MlogHistory.setText(resourceMap.getString("MlogHistory.text")); // NOI18N
        MlogHistory.setName("MlogHistory"); // NOI18N
        MlogHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlogHistoryActionPerformed(evt);
            }
        });
        fileMenu.add(MlogHistory);

        Manalisa.setIcon(resourceMap.getIcon("Manalisa.icon")); // NOI18N
        Manalisa.setText(resourceMap.getString("Manalisa.text")); // NOI18N
        Manalisa.setName("Manalisa"); // NOI18N

        Manalisastokbrg.setText(resourceMap.getString("Manalisastokbrg.text")); // NOI18N
        Manalisastokbrg.setName("Manalisastokbrg"); // NOI18N
        Manalisa.add(Manalisastokbrg);

        fileMenu.add(Manalisa);

        MSearchingBarang.setIcon(resourceMap.getIcon("MSearchingBarang.icon")); // NOI18N
        MSearchingBarang.setText(resourceMap.getString("MSearchingBarang.text")); // NOI18N
        MSearchingBarang.setName("MSearchingBarang"); // NOI18N
        MSearchingBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSearchingBarangActionPerformed(evt);
            }
        });
        fileMenu.add(MSearchingBarang);

        menuBar.add(fileMenu);

        Mtransaksi.setIcon(resourceMap.getIcon("Mtransaksi.icon")); // NOI18N
        Mtransaksi.setText(resourceMap.getString("Mtransaksi.text")); // NOI18N
        Mtransaksi.setName("Mtransaksi"); // NOI18N

        Mjurnal.setIcon(resourceMap.getIcon("Mjurnal.icon")); // NOI18N
        Mjurnal.setText(resourceMap.getString("Mjurnal.text")); // NOI18N
        Mjurnal.setName("Mjurnal"); // NOI18N
        Mjurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MjurnalActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mjurnal);

        MdeliveryOrder.setIcon(resourceMap.getIcon("MdeliveryOrder.icon")); // NOI18N
        MdeliveryOrder.setText(resourceMap.getString("MdeliveryOrder.text")); // NOI18N
        MdeliveryOrder.setName("MdeliveryOrder"); // NOI18N
        MdeliveryOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MdeliveryOrderActionPerformed(evt);
            }
        });
        Mtransaksi.add(MdeliveryOrder);

        Mpenjualan.setIcon(resourceMap.getIcon("Mpenjualan.icon")); // NOI18N
        Mpenjualan.setText(resourceMap.getString("Mpenjualan.text")); // NOI18N
        Mpenjualan.setName("Mpenjualan"); // NOI18N
        Mpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpenjualanActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mpenjualan);

        Mpembelian.setIcon(resourceMap.getIcon("Mpembelian.icon")); // NOI18N
        Mpembelian.setText(resourceMap.getString("Mpembelian.text")); // NOI18N
        Mpembelian.setName("Mpembelian"); // NOI18N
        Mpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpembelianActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mpembelian);

        Mhutang.setIcon(resourceMap.getIcon("Mhutang.icon")); // NOI18N
        Mhutang.setText(resourceMap.getString("Mhutang.text")); // NOI18N
        Mhutang.setName("Mhutang"); // NOI18N
        Mhutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MhutangActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mhutang);

        Mpiutang.setIcon(resourceMap.getIcon("Mpiutang.icon")); // NOI18N
        Mpiutang.setText(resourceMap.getString("Mpiutang.text")); // NOI18N
        Mpiutang.setName("Mpiutang"); // NOI18N
        Mpiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpiutangActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mpiutang);

        Mtutupbuku.setIcon(resourceMap.getIcon("Mtutupbuku.icon")); // NOI18N
        Mtutupbuku.setText(resourceMap.getString("Mtutupbuku.text")); // NOI18N
        Mtutupbuku.setName("Mtutupbuku"); // NOI18N
        Mtutupbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtutupbukuActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mtutupbuku);

        Mtutupstok.setIcon(resourceMap.getIcon("Mtutupstok.icon")); // NOI18N
        Mtutupstok.setText(resourceMap.getString("Mtutupstok.text")); // NOI18N
        Mtutupstok.setName("Mtutupstok"); // NOI18N
        Mtutupstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MtutupstokActionPerformed(evt);
            }
        });
        Mtransaksi.add(Mtutupstok);

        MkoreksiStok.setIcon(resourceMap.getIcon("MkoreksiStok.icon")); // NOI18N
        MkoreksiStok.setText(resourceMap.getString("MkoreksiStok.text")); // NOI18N
        MkoreksiStok.setName("MkoreksiStok"); // NOI18N
        MkoreksiStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MkoreksiStokActionPerformed(evt);
            }
        });
        Mtransaksi.add(MkoreksiStok);

        menuBar.add(Mtransaksi);

        Mlaporan.setIcon(resourceMap.getIcon("Mlaporan.icon")); // NOI18N
        Mlaporan.setText(resourceMap.getString("Mlaporan.text")); // NOI18N
        Mlaporan.setName("Mlaporan"); // NOI18N

        Mlappembelian.setText(resourceMap.getString("Mlappembelian.text")); // NOI18N
        Mlappembelian.setName("Mlappembelian"); // NOI18N

        jMenuItem29.setText(resourceMap.getString("jMenuItem29.text")); // NOI18N
        jMenuItem29.setName("jMenuItem29"); // NOI18N
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        Mlappembelian.add(jMenuItem29);

        jMenuItem30.setText(resourceMap.getString("jMenuItem30.text")); // NOI18N
        jMenuItem30.setName("jMenuItem30"); // NOI18N
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        Mlappembelian.add(jMenuItem30);

        jMenuItem33.setText(resourceMap.getString("jMenuItem33.text")); // NOI18N
        jMenuItem33.setName("jMenuItem33"); // NOI18N
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        Mlappembelian.add(jMenuItem33);

        Mlaporan.add(Mlappembelian);

        Mreturpembelian.setText(resourceMap.getString("Mreturpembelian.text")); // NOI18N
        Mreturpembelian.setName("Mreturpembelian"); // NOI18N

        Mreturbelifaktur.setText(resourceMap.getString("Mreturbelifaktur.text")); // NOI18N
        Mreturbelifaktur.setName("Mreturbelifaktur"); // NOI18N
        Mreturbelifaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MreturbelifakturActionPerformed(evt);
            }
        });
        Mreturpembelian.add(Mreturbelifaktur);

        Mrekapreturbeli.setText(resourceMap.getString("Mrekapreturbeli.text")); // NOI18N
        Mrekapreturbeli.setName("Mrekapreturbeli"); // NOI18N
        Mrekapreturbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrekapreturbeliActionPerformed(evt);
            }
        });
        Mreturpembelian.add(Mrekapreturbeli);

        Mlaporan.add(Mreturpembelian);

        MlapPenjualan.setText(resourceMap.getString("MlapPenjualan.text")); // NOI18N
        MlapPenjualan.setName("MlapPenjualan"); // NOI18N

        jMenuItem11.setText(resourceMap.getString("jMenuItem11.text")); // NOI18N
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        MlapPenjualan.add(jMenuItem11);

        jMenuItem26.setText(resourceMap.getString("jMenuItem26.text")); // NOI18N
        jMenuItem26.setName("jMenuItem26"); // NOI18N
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        MlapPenjualan.add(jMenuItem26);

        jMenuItem27.setText(resourceMap.getString("jMenuItem27.text")); // NOI18N
        jMenuItem27.setName("jMenuItem27"); // NOI18N
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        MlapPenjualan.add(jMenuItem27);

        jMenuItem28.setText(resourceMap.getString("jMenuItem28.text")); // NOI18N
        jMenuItem28.setName("jMenuItem28"); // NOI18N
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        MlapPenjualan.add(jMenuItem28);

        jMenuItem21.setText(resourceMap.getString("jMenuItem21.text")); // NOI18N
        jMenuItem21.setName("jMenuItem21"); // NOI18N
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        MlapPenjualan.add(jMenuItem21);

        Mlaporan.add(MlapPenjualan);

        Mreturpenjualan.setText(resourceMap.getString("Mreturpenjualan.text")); // NOI18N
        Mreturpenjualan.setName("Mreturpenjualan"); // NOI18N

        Mreturjualfaktur.setText(resourceMap.getString("Mreturjualfaktur.text")); // NOI18N
        Mreturjualfaktur.setName("Mreturjualfaktur"); // NOI18N
        Mreturjualfaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MreturjualfakturActionPerformed(evt);
            }
        });
        Mreturpenjualan.add(Mreturjualfaktur);

        Mrekapreturjual.setText(resourceMap.getString("Mrekapreturjual.text")); // NOI18N
        Mrekapreturjual.setName("Mrekapreturjual"); // NOI18N
        Mrekapreturjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrekapreturjualActionPerformed(evt);
            }
        });
        Mreturpenjualan.add(Mrekapreturjual);

        Mlaporan.add(Mreturpenjualan);

        Mlapdeliveryorder.setText(resourceMap.getString("Mlapdeliveryorder.text")); // NOI18N
        Mlapdeliveryorder.setName("Mlapdeliveryorder"); // NOI18N

        MlapFakturDO.setText(resourceMap.getString("MlapFakturDO.text")); // NOI18N
        MlapFakturDO.setName("MlapFakturDO"); // NOI18N
        MlapFakturDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapFakturDOActionPerformed(evt);
            }
        });
        Mlapdeliveryorder.add(MlapFakturDO);

        MrekapDO.setText(resourceMap.getString("MrekapDO.text")); // NOI18N
        MrekapDO.setName("MrekapDO"); // NOI18N
        MrekapDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrekapDOActionPerformed(evt);
            }
        });
        Mlapdeliveryorder.add(MrekapDO);

        Mlaporan.add(Mlapdeliveryorder);

        MlapBarang.setText(resourceMap.getString("MlapBarang.text")); // NOI18N
        MlapBarang.setName("MlapBarang"); // NOI18N

        jMenuItem14.setText(resourceMap.getString("jMenuItem14.text")); // NOI18N
        jMenuItem14.setName("jMenuItem14"); // NOI18N
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        MlapBarang.add(jMenuItem14);

        jMenuItem25.setText(resourceMap.getString("jMenuItem25.text")); // NOI18N
        jMenuItem25.setName("jMenuItem25"); // NOI18N
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        MlapBarang.add(jMenuItem25);

        jMenuItem20.setText(resourceMap.getString("jMenuItem20.text")); // NOI18N
        jMenuItem20.setName("jMenuItem20"); // NOI18N
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        MlapBarang.add(jMenuItem20);

        jMenuItem32.setText(resourceMap.getString("jMenuItem32.text")); // NOI18N
        jMenuItem32.setName("jMenuItem32"); // NOI18N
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        MlapBarang.add(jMenuItem32);

        Mlaporan.add(MlapBarang);

        MlapHutang.setText(resourceMap.getString("MlapHutang.text")); // NOI18N
        MlapHutang.setName("MlapHutang"); // NOI18N

        MlapUmurHutang.setText(resourceMap.getString("MlapUmurHutang.text")); // NOI18N
        MlapUmurHutang.setName("MlapUmurHutang"); // NOI18N
        MlapUmurHutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapUmurHutangActionPerformed(evt);
            }
        });
        MlapHutang.add(MlapUmurHutang);

        Mlaporan.add(MlapHutang);

        MlapPiutang.setText(resourceMap.getString("MlapPiutang.text")); // NOI18N
        MlapPiutang.setName("MlapPiutang"); // NOI18N

        MlapUmurPiutang.setText(resourceMap.getString("MlapUmurPiutang.text")); // NOI18N
        MlapUmurPiutang.setName("MlapUmurPiutang"); // NOI18N
        MlapUmurPiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapUmurPiutangActionPerformed(evt);
            }
        });
        MlapPiutang.add(MlapUmurPiutang);

        MlapUmurPiutangPersales.setText(resourceMap.getString("MlapUmurPiutangPersales.text")); // NOI18N
        MlapUmurPiutangPersales.setName("MlapUmurPiutangPersales"); // NOI18N
        MlapUmurPiutangPersales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapUmurPiutangPersalesActionPerformed(evt);
            }
        });
        MlapPiutang.add(MlapUmurPiutangPersales);

        Mlaporan.add(MlapPiutang);

        MLapPerkiraan.setText(resourceMap.getString("MLapPerkiraan.text")); // NOI18N
        MLapPerkiraan.setName("MLapPerkiraan"); // NOI18N
        MLapPerkiraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLapPerkiraanActionPerformed(evt);
            }
        });
        Mlaporan.add(MLapPerkiraan);

        MlapFakturPajak.setText(resourceMap.getString("MlapFakturPajak.text")); // NOI18N
        MlapFakturPajak.setName("MlapFakturPajak"); // NOI18N
        MlapFakturPajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapFakturPajakActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapFakturPajak);

        MlapTutupBuku.setText(resourceMap.getString("MlapTutupBuku.text")); // NOI18N
        MlapTutupBuku.setName("MlapTutupBuku"); // NOI18N
        MlapTutupBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapTutupBukuActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapTutupBuku);

        MlapJurnal.setText(resourceMap.getString("MlapJurnal.text")); // NOI18N
        MlapJurnal.setName("MlapJurnal"); // NOI18N
        MlapJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapJurnalActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapJurnal);

        MlapBukuBesar.setText(resourceMap.getString("MlapBukuBesar.text")); // NOI18N
        MlapBukuBesar.setName("MlapBukuBesar"); // NOI18N
        MlapBukuBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapBukuBesarActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapBukuBesar);

        MlapNeraca.setText(resourceMap.getString("MlapNeraca.text")); // NOI18N
        MlapNeraca.setName("MlapNeraca"); // NOI18N
        MlapNeraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapNeracaActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapNeraca);

        MlapRugiLaba.setText(resourceMap.getString("MlapRugiLaba.text")); // NOI18N
        MlapRugiLaba.setName("MlapRugiLaba"); // NOI18N
        MlapRugiLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapRugiLabaActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapRugiLaba);

        MlapEkuitas.setText(resourceMap.getString("MlapEkuitas.text")); // NOI18N
        MlapEkuitas.setName("MlapEkuitas"); // NOI18N
        MlapEkuitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlapEkuitasActionPerformed(evt);
            }
        });
        Mlaporan.add(MlapEkuitas);

        menuBar.add(Mlaporan);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getActionMap(Zaren.class, this);
        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        Mkeluar.setText(resourceMap.getString("Mkeluar.text")); // NOI18N
        Mkeluar.setName("Mkeluar"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        Mkeluar.add(exitMenuItem);

        menuBar.add(Mkeluar);

        setJMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void MuserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MuserAccountActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormUser p = new com.eigher.form.FormUser();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MuserAccountActionPerformed

    private void MeditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeditPasswordActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormEditUser p = new com.eigher.form.FormEditUser();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MeditPasswordActionPerformed

    private void MaktivaTetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaktivaTetapActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormAktivaTetap p = new com.eigher.form.FormAktivaTetap();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MaktivaTetapActionPerformed

    private void MperkiraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MperkiraanActionPerformed
        // TODO add your handling code here:
        konek();
        FormPerkiraan p = new FormPerkiraan();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MperkiraanActionPerformed

    private void MMerkBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMerkBarangActionPerformed
        // TODO add your handling code here:
        konek();
        FormJenisBarang p = new FormJenisBarang();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MMerkBarangActionPerformed

    private void MkategoriBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MkategoriBrgActionPerformed
        // TODO add your handling code here:
        konek();
        FormKategori p = new FormKategori();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MkategoriBrgActionPerformed

    private void MdataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MdataBarangActionPerformed
        // TODO add your handling code here:
        konek();
        FormBarang b = new FormBarang();
        b.toFront();
        panelCool1.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_MdataBarangActionPerformed

    private void MpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpelangganActionPerformed
        // TODO add your handling code here:
        konek();
        FormPelanggan p = new FormPelanggan();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MpelangganActionPerformed

    private void MsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsupplierActionPerformed
        // TODO add your handling code here:
        konek();
        FormSupplier p = new FormSupplier();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MsupplierActionPerformed

    private void MsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsalesActionPerformed
        // TODO add your handling code here:
        konek();
        FormSales p = new FormSales();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MsalesActionPerformed

    private void MbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbankActionPerformed
        // TODO add your handling code here:
        konek();
        FormBank p = new FormBank();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MbankActionPerformed

    private void MsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsettingActionPerformed
        // TODO add your handling code here:
        konek();
        FormSetting p = new FormSetting();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MsettingActionPerformed

    private void MsettingStatPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsettingStatPeriodeActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormKontrolPeriode p = new com.eigher.form.FormKontrolPeriode();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MsettingStatPeriodeActionPerformed

    private void MlogHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlogHistoryActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormLogHistory p = new com.eigher.form.FormLogHistory();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlogHistoryActionPerformed

    private void MjurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MjurnalActionPerformed
        // TODO add your handling code here:
        konek();
        FormJurnal p = new FormJurnal();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MjurnalActionPerformed

    private void MdeliveryOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MdeliveryOrderActionPerformed
        // TODO add your handling code here:
        konek();
        FormDO p = new FormDO();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MdeliveryOrderActionPerformed

    private void MpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpenjualanActionPerformed
        // TODO add your handling code here:
        konek();
        FormPenjualan p = new FormPenjualan();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MpenjualanActionPerformed

    private void MpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpembelianActionPerformed
        // TODO add your handling code here:
        konek();
        FormPembelian p = new FormPembelian();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MpembelianActionPerformed

    private void MpiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpiutangActionPerformed
        // TODO add your handling code here:
        konek();
        DialogPiutang p = new DialogPiutang(null, false);
        p.setVisible(true);
    }//GEN-LAST:event_MpiutangActionPerformed

    private void MkoreksiStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MkoreksiStokActionPerformed
        // TODO add your handling code here:
        konek();
        FKoreksiStok p = new FKoreksiStok();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MkoreksiStokActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
//            HashMap parameter=new HashMap();
//        JasperPrint jasperPrint=null;
//        try { 
//                jasperPrint = JasperFillManager.fillReport("report\\Barang.jasper", parameter, koneksi.getKoneksiJ());
//            JasperViewer.viewReport(jasperPrint,false);
//        } catch (Exception ex) {
//            System.out.print(ex.toString());
//            //Logger.getLogger(formlaporan.class.getName()).log(Level.SEVERE, null, ex);
//        }
        konek();
        FlapBarangPerMerk p = new FlapBarangPerMerk();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        konek();
        FlapPembelianHarian p = new FlapPembelianHarian();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        konek();
        FlapPerFakturBeli p = new FlapPerFakturBeli();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FRekapPembelianharian p = new com.eigher.form.FRekapPembelianharian();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void MreturbelifakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MreturbelifakturActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.LapReturBeliFaktur p = new com.eigher.form.LapReturBeliFaktur();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MreturbelifakturActionPerformed

    private void MrekapreturbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrekapreturbeliActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FRekapReturBeli p = new com.eigher.form.FRekapReturBeli();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MrekapreturbeliActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        konek();
        LaporanPenjualanHarianFormLama p = new LaporanPenjualanHarianFormLama();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        konek();
        FlapJualPerSales p = new FlapJualPerSales();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        konek();
        FlapPerFaktur p = new FlapPerFaktur();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        konek();
        FRekapJualPerPelanggan p = new FRekapJualPerPelanggan();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        konek();
        FRekapPenjualanHarianLama p = new FRekapPenjualanHarianLama();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void MreturjualfakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MreturjualfakturActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.LapReturJualFaktur p = new com.eigher.form.LapReturJualFaktur();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MreturjualfakturActionPerformed

    private void MrekapreturjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrekapreturjualActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FRekapReturJual p = new com.eigher.form.FRekapReturJual();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MrekapreturjualActionPerformed

    private void MlapFakturDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapFakturDOActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FlapFakturDistribusi p = new com.eigher.form.FlapFakturDistribusi();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapFakturDOActionPerformed

    private void MrekapDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrekapDOActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FRekapDistribusi p = new com.eigher.form.FRekapDistribusi();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MrekapDOActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        konek();
        FlapBarangPerKategori p = new FlapBarangPerKategori();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.LaporanKartuStok p = new com.eigher.form.LaporanKartuStok();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
        konek();
        FPersediaanBrgDagang p = new FPersediaanBrgDagang();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void MlapUmurHutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapUmurHutangActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FLapAnalisaUmurHutangLama p = new com.eigher.form.FLapAnalisaUmurHutangLama();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapUmurHutangActionPerformed

    private void MlapUmurPiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapUmurPiutangActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FLapAnalisaUmurPiutangLama p = new com.eigher.form.FLapAnalisaUmurPiutangLama();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapUmurPiutangActionPerformed

    private void MlapUmurPiutangPersalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapUmurPiutangPersalesActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FLapUmurPiutangPersales p = new com.eigher.form.FLapUmurPiutangPersales();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapUmurPiutangPersalesActionPerformed

    private void MLapPerkiraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLapPerkiraanActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FLapDataPerkiraan p = new com.eigher.form.FLapDataPerkiraan();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MLapPerkiraanActionPerformed

    private void MlapFakturPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapFakturPajakActionPerformed
        // TODO add your handling code here:
        konek();
        FormFakturPajak p = new FormFakturPajak();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapFakturPajakActionPerformed

    private void MlapTutupBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapTutupBukuActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FLapTutupBuku p = new com.eigher.form.FLapTutupBuku();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapTutupBukuActionPerformed

    private void MlapJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapJurnalActionPerformed
        // TODO add your handling code here:
        konek();
        LaporanJurnalForm p = new LaporanJurnalForm();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapJurnalActionPerformed

    private void MlapBukuBesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapBukuBesarActionPerformed
        // TODO add your handling code here:
        konek();
        LaporanBukuBesarDetailForm p = new LaporanBukuBesarDetailForm();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapBukuBesarActionPerformed

    private void MlapNeracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapNeracaActionPerformed
        // TODO add your handling code here:
        konek();
        LaporanNeracaForm p = new LaporanNeracaForm();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapNeracaActionPerformed

    private void MlapRugiLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapRugiLabaActionPerformed
        // TODO add your handling code here:
        konek();
        LaporanLabaRugiForm p = new LaporanLabaRugiForm();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapRugiLabaActionPerformed

    private void MlapEkuitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlapEkuitasActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.LaporanEkuitas p = new com.eigher.form.LaporanEkuitas();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MlapEkuitasActionPerformed

    private void MloginuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MloginuserActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormLogin p = new com.eigher.form.FormLogin();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MloginuserActionPerformed

    private void MlogOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlogOfActionPerformed
        // TODO add your handling code here:
        konek();
        com.eigher.form.FormLogin p = new com.eigher.form.FormLogin();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
        LblJenis.setText("");
        Lblgroup.setText("");
        nonaktif();
    }//GEN-LAST:event_MlogOfActionPerformed

    private void MtutupbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtutupbukuActionPerformed
        // TODO add your handling code here:
        konek();
        FormTutupBuku p = new FormTutupBuku();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MtutupbukuActionPerformed

    private void MhutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MhutangActionPerformed
        // TODO add your handling code here:
        konek();
        DialogHutang p = new DialogHutang(null, false);
        p.setVisible(true);
    }//GEN-LAST:event_MhutangActionPerformed

    private void MtutupstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MtutupstokActionPerformed
        // TODO add your handling code here:
        konek();
        FormTutupStok p = new FormTutupStok();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MtutupstokActionPerformed

    private void MSearchingBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSearchingBarangActionPerformed
        // TODO add your handling code here:
        konek();
        FormSearchBarang p = new FormSearchBarang();
        p.toFront();
        panelCool1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MSearchingBarangActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LblJenis;
    private javax.swing.JLabel LblJenis1;
    private javax.swing.JLabel LblJenis2;
    private javax.swing.JLabel LblJenis3;
    private javax.swing.JLabel LblJenis4;
    public static javax.swing.JLabel Lblgroup;
    public static javax.swing.JMenuItem MLapPerkiraan;
    private javax.swing.JMenuItem MMerkBarang;
    public static javax.swing.JMenuItem MSearchingBarang;
    public static javax.swing.JMenuItem MaktivaTetap;
    public static javax.swing.JMenu Manalisa;
    private javax.swing.JMenuItem Manalisastokbrg;
    public static javax.swing.JMenuItem Mbank;
    private static javax.swing.JMenu Mbarang;
    private javax.swing.JMenuItem MdataBarang;
    public static javax.swing.JMenuItem MdeliveryOrder;
    public static javax.swing.JMenuItem MeditPassword;
    public static javax.swing.JMenuItem Mhutang;
    public static javax.swing.JMenuItem Mjurnal;
    private javax.swing.JMenuItem MkategoriBrg;
    private javax.swing.JMenu Mkeluar;
    public static javax.swing.JMenuItem MkoreksiStok;
    public static javax.swing.JMenu MlapBarang;
    public static javax.swing.JMenuItem MlapBukuBesar;
    public static javax.swing.JMenuItem MlapEkuitas;
    private javax.swing.JMenuItem MlapFakturDO;
    public static javax.swing.JMenuItem MlapFakturPajak;
    public static javax.swing.JMenu MlapHutang;
    public static javax.swing.JMenuItem MlapJurnal;
    public static javax.swing.JMenuItem MlapNeraca;
    public static javax.swing.JMenu MlapPenjualan;
    public static javax.swing.JMenu MlapPiutang;
    public static javax.swing.JMenuItem MlapRugiLaba;
    public static javax.swing.JMenuItem MlapTutupBuku;
    private javax.swing.JMenuItem MlapUmurHutang;
    private javax.swing.JMenuItem MlapUmurPiutang;
    private javax.swing.JMenuItem MlapUmurPiutangPersales;
    public static javax.swing.JMenu Mlapdeliveryorder;
    private javax.swing.JMenu Mlaporan;
    public static javax.swing.JMenu Mlappembelian;
    public static javax.swing.JMenuItem MlogHistory;
    public static javax.swing.JMenuItem MlogOf;
    private javax.swing.JMenu Mlogin;
    public static javax.swing.JMenuItem Mloginuser;
    public static javax.swing.JMenuItem Mpelanggan;
    public static javax.swing.JMenuItem Mpembelian;
    public static javax.swing.JMenuItem Mpenjualan;
    public static javax.swing.JMenuItem Mperkiraan;
    public static javax.swing.JMenuItem Mpiutang;
    private javax.swing.JMenuItem MrekapDO;
    private javax.swing.JMenuItem Mrekapreturbeli;
    private javax.swing.JMenuItem Mrekapreturjual;
    private javax.swing.JMenuItem Mreturbelifaktur;
    private javax.swing.JMenuItem Mreturjualfaktur;
    public static javax.swing.JMenu Mreturpembelian;
    public static javax.swing.JMenu Mreturpenjualan;
    public static javax.swing.JMenuItem Msales;
    public static javax.swing.JMenuItem Msetting;
    public static javax.swing.JMenuItem MsettingStatPeriode;
    public static javax.swing.JMenuItem Msupplier;
    private javax.swing.JMenu Mtransaksi;
    public static javax.swing.JMenuItem Mtutupbuku;
    public static javax.swing.JMenuItem Mtutupstok;
    public static javax.swing.JMenuItem MuserAccount;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuBar menuBar;
    public static com.erv.model.DesktopCool panelCool1;
    // End of variables declaration//GEN-END:variables

    public static void aktif() {
        MuserAccount.setVisible(true);
        MeditPassword.setVisible(true);
        Mperkiraan.setVisible(true);
        MaktivaTetap.setVisible(true);
        Mbarang.setVisible(true);
        Mpelanggan.setVisible(true);
        Msupplier.setVisible(true);
        Msales.setVisible(true);
        Mbank.setVisible(true);
        Msetting.setVisible(true);
        MsettingStatPeriode.setVisible(true);
        MlogHistory.setVisible(true);
        Manalisa.setVisible(true);
        MSearchingBarang.setVisible(true);
        Mjurnal.setVisible(true);
        MdeliveryOrder.setVisible(true);
        Mpenjualan.setVisible(true);
        Mpembelian.setVisible(true);
        Mhutang.setVisible(true);
        Mpiutang.setVisible(true);
        Mtutupbuku.setVisible(true);
        Mtutupstok.setVisible(true);
        MkoreksiStok.setVisible(true);
        Mlappembelian.setVisible(true);
        MlapPenjualan.setVisible(true);
        Mreturpembelian.setVisible(true);
        Mreturpenjualan.setVisible(true);
        Mlapdeliveryorder.setVisible(true);
        MlapBarang.setVisible(true);
        MlapHutang.setVisible(true);
        MlapPiutang.setVisible(true);
        MLapPerkiraan.setVisible(true);
        MlapFakturPajak.setVisible(true);
        MlapTutupBuku.setVisible(true);
        MlapJurnal.setVisible(true);
        MlapBukuBesar.setVisible(true);
        MlapNeraca.setVisible(true);
        MlapRugiLaba.setVisible(true);
        MlapEkuitas.setVisible(true);
    }

    public static void nonaktif() {
        MuserAccount.setVisible(false);
        MeditPassword.setVisible(false);
        Mperkiraan.setVisible(false);
        MaktivaTetap.setVisible(false);
        Mbarang.setVisible(false);
        Mpelanggan.setVisible(false);
        Msupplier.setVisible(false);
        Msales.setVisible(false);
        Mbank.setVisible(false);
        Msetting.setVisible(false);
        MsettingStatPeriode.setVisible(false);
        MlogHistory.setVisible(false);
        Manalisa.setVisible(false);
        MSearchingBarang.setVisible(false);
        Mjurnal.setVisible(false);
        MdeliveryOrder.setVisible(false);
        Mpenjualan.setVisible(false);
        Mpembelian.setVisible(false);
        Mhutang.setVisible(false);
        Mpiutang.setVisible(false);
        Mtutupbuku.setVisible(false);
        Mtutupstok.setVisible(false);
        MkoreksiStok.setVisible(false);
        Mlappembelian.setVisible(false);
        MlapPenjualan.setVisible(false);
        Mreturpembelian.setVisible(false);
        Mreturpenjualan.setVisible(false);
        Mlapdeliveryorder.setVisible(false);
        MlapBarang.setVisible(false);
        MlapHutang.setVisible(false);
        MlapPiutang.setVisible(false);
        MLapPerkiraan.setVisible(false);
        MlapFakturPajak.setVisible(false);
        MlapTutupBuku.setVisible(false);
        MlapJurnal.setVisible(false);
        MlapBukuBesar.setVisible(false);
        MlapNeraca.setVisible(false);
        MlapRugiLaba.setVisible(false);
        MlapEkuitas.setVisible(false);
    }

    public static void pembelianakses() {
        MuserAccount.setVisible(false);
        MeditPassword.setVisible(true);
        Mperkiraan.setVisible(false);
        MaktivaTetap.setVisible(false);
        Mbarang.setVisible(true);
        Mpelanggan.setVisible(false);
        Msupplier.setVisible(true);
        Msales.setVisible(false);
        Mbank.setVisible(false);
        Msetting.setVisible(false);
        MsettingStatPeriode.setVisible(false);
        MlogHistory.setVisible(false);
        Manalisa.setVisible(false);
        MSearchingBarang.setVisible(true);
        Mjurnal.setVisible(false);
        MdeliveryOrder.setVisible(false);
        Mpenjualan.setVisible(false);
        Mpembelian.setVisible(true);
//    FormPembelian.btnBayarPenerimaanHutang.setVisible(false);
//    FormPembelian.btnDeletePembelianAll.setVisible(false);
        Mhutang.setVisible(false);
        Mpiutang.setVisible(false);
        Mtutupbuku.setVisible(false);
        Mtutupstok.setVisible(false);
        MkoreksiStok.setVisible(false);
        Mlappembelian.setVisible(true);
        MlapPenjualan.setVisible(true);
        Mreturpembelian.setVisible(true);
        Mreturpenjualan.setVisible(false);
        Mlapdeliveryorder.setVisible(true);
        MlapBarang.setVisible(true);
        MlapHutang.setVisible(false);
        MlapPiutang.setVisible(false);
        MLapPerkiraan.setVisible(false);
        MlapFakturPajak.setVisible(false);
        MlapTutupBuku.setVisible(false);
        MlapJurnal.setVisible(false);
        MlapBukuBesar.setVisible(false);
        MlapNeraca.setVisible(false);
        MlapRugiLaba.setVisible(false);
        MlapEkuitas.setVisible(false);
    }

    public static void penjualanakses() {
        MuserAccount.setVisible(false);
        MeditPassword.setVisible(true);
        Mperkiraan.setVisible(false);
        MaktivaTetap.setVisible(false);
        Mbarang.setVisible(false);
        Mpelanggan.setVisible(true);
        Msupplier.setVisible(false);
        Msales.setVisible(false);
        Mbank.setVisible(false);
        Msetting.setVisible(false);
        MsettingStatPeriode.setVisible(false);
        MlogHistory.setVisible(false);
        Manalisa.setVisible(false);
        MSearchingBarang.setVisible(true);
        Mjurnal.setVisible(false);
        MdeliveryOrder.setVisible(true);
        Mpenjualan.setVisible(true);
//    FormPenjualan.btnBayarPenerimaanPiutang.setVisible(false);
//    FormPenjualan.btnDeletePenjualanAll.setVisible(false);
        Mpembelian.setVisible(false);
        Mhutang.setVisible(false);
        Mpiutang.setVisible(false);
        Mtutupbuku.setVisible(false);
        Mtutupstok.setVisible(false);
        MkoreksiStok.setVisible(false);
        Mlappembelian.setVisible(false);
        MlapPenjualan.setVisible(true);
        Mreturpembelian.setVisible(false);
        Mreturpenjualan.setVisible(true);
        Mlapdeliveryorder.setVisible(true);
        MlapBarang.setVisible(true);
        MlapHutang.setVisible(false);
        MlapPiutang.setVisible(false);
        MLapPerkiraan.setVisible(false);
        MlapFakturPajak.setVisible(false);
        MlapTutupBuku.setVisible(false);
        MlapJurnal.setVisible(false);
        MlapBukuBesar.setVisible(false);
        MlapNeraca.setVisible(false);
        MlapRugiLaba.setVisible(false);
        MlapEkuitas.setVisible(false);
    }

    public static void accountingakses() {
        MuserAccount.setVisible(false);
        MeditPassword.setVisible(true);
        Mperkiraan.setVisible(true);
        MaktivaTetap.setVisible(true);
        Mbarang.setVisible(false);
        Mpelanggan.setVisible(true);
        Msupplier.setVisible(false);
        Msales.setVisible(false);
        Mbank.setVisible(false);
        Msetting.setVisible(false);
        MsettingStatPeriode.setVisible(false);
        MlogHistory.setVisible(false);
        Manalisa.setVisible(false);
        MSearchingBarang.setVisible(false);
        Mjurnal.setVisible(true);
        MdeliveryOrder.setVisible(false);
        Mpenjualan.setVisible(false);
        Mpembelian.setVisible(false);
        Mhutang.setVisible(true);
        Mpiutang.setVisible(true);
        Mtutupbuku.setVisible(false);
        Mtutupstok.setVisible(false);
        MkoreksiStok.setVisible(false);
        Mlappembelian.setVisible(true);
        MlapPenjualan.setVisible(true);
        Mreturpembelian.setVisible(true);
        Mreturpenjualan.setVisible(true);
        Mlapdeliveryorder.setVisible(true);
        MlapBarang.setVisible(true);
        MlapHutang.setVisible(true);
        MlapPiutang.setVisible(true);
        MLapPerkiraan.setVisible(true);
        MlapFakturPajak.setVisible(true);
        MlapTutupBuku.setVisible(true);
        MlapJurnal.setVisible(true);
        MlapBukuBesar.setVisible(true);
        MlapNeraca.setVisible(true);
        MlapRugiLaba.setVisible(true);
        MlapEkuitas.setVisible(true);
    }

    public static void pajakakses() {
        MuserAccount.setVisible(false);
        MeditPassword.setVisible(true);
        Mperkiraan.setVisible(false);
        MaktivaTetap.setVisible(false);
        Mbarang.setVisible(false);
        Mpelanggan.setVisible(true);
        Msupplier.setVisible(false);
        Msales.setVisible(false);
        Mbank.setVisible(false);
        Msetting.setVisible(false);
        MsettingStatPeriode.setVisible(false);
        MlogHistory.setVisible(false);
        Manalisa.setVisible(false);
        MSearchingBarang.setVisible(false);
        Mjurnal.setVisible(false);
        MdeliveryOrder.setVisible(false);
        Mpenjualan.setVisible(false);
        Mpembelian.setVisible(false);
        Mhutang.setVisible(false);
        Mpiutang.setVisible(false);
        Mtutupbuku.setVisible(false);
        Mtutupstok.setVisible(false);
        MkoreksiStok.setVisible(false);
        Mlappembelian.setVisible(false);
        MlapPenjualan.setVisible(true);
        Mreturpembelian.setVisible(false);
        Mreturpenjualan.setVisible(false);
        Mlapdeliveryorder.setVisible(false);
        MlapBarang.setVisible(false);
        MlapHutang.setVisible(false);
        MlapPiutang.setVisible(false);
        MLapPerkiraan.setVisible(false);
        MlapFakturPajak.setVisible(true);
        MlapTutupBuku.setVisible(false);
        MlapJurnal.setVisible(false);
        MlapBukuBesar.setVisible(false);
        MlapNeraca.setVisible(false);
        MlapRugiLaba.setVisible(false);
        MlapEkuitas.setVisible(false);
    }
    void konek(){
//        try {
//            if(con==null || con.isClosed()){
//            Class.forName("org.h2.Driver").getInterfaces();
//            con = DriverManager.getConnection("jdbc:h2:tcp://"+IPDB+"/~/penjualan", "", "");
//            koneksi.con = con;
//            }
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(panelCool1, ex.toString()+" "+IPDB);
//        }
    }
}