/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erv.view;

import com.erv.controller.GiroController;
import com.erv.db.koneksi;
import com.erv.db.pelangganDao;
import com.erv.function.ArrayTable;
import com.erv.function.ExecuteQuery;
import com.erv.fungsi.DecimalFormatRenderer;
import com.erv.model.GiroModel;
import com.erv.model.pelanggan;
import datechooser.beans.DateChooserCombo;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ervan
 */
public class GiroBayarView extends javax.swing.JPanel {

    /**
     * Creates new form GiroBayarView
     */
    com.erv.function.Util u = new com.erv.function.Util();
    GiroModel model;
    GiroController controller;
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    
    public GiroBayarView() {
        model = new GiroModel();
        controller = new GiroController();
        controller.setModel(model); 
        initComponents();
        cboBulanCari.setSelectedIndex(u.blnsekarang - 1);
        txtTahun.setText("" + u.thnsekarang);
        jScrollPane2.setVisible(false);
        jScrollPane2.setSize(350, 150);
        TanggalCair.setDateFormat(df); 
    }

    public JTable getTabelData() {
        return tabelData;
    }

    public void setTabelData(JTable tabelData) {
        this.tabelData = tabelData;
    }

    public DateChooserCombo getTanggalCair() {
        return TanggalCair;
    }

    public void setTanggalCair(DateChooserCombo TanggalCair) {
        this.TanggalCair = TanggalCair;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        txtPelangganCari = new javax.swing.JTextField();
        txtNamaPelangganCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboBulanCari = new javax.swing.JComboBox();
        txtTahun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TanggalCair = new datechooser.beans.DateChooserCombo();

        setName("Form"); // NOI18N
        setLayout(null);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelPelanggan.setName("tabelPelanggan"); // NOI18N
        tabelPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelPelangganKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        add(jScrollPane2);
        jScrollPane2.setBounds(160, 30, 70, 30);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(GiroBayarView.class);
        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(10, 10, 113, 15);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelData.setName("tabelData"); // NOI18N
        jScrollPane1.setViewportView(tabelData);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 106, 850, 390);

        txtPelangganCari.setFont(resourceMap.getFont("txtPelangganCari.font")); // NOI18N
        txtPelangganCari.setText(resourceMap.getString("txtPelangganCari.text")); // NOI18N
        txtPelangganCari.setName("txtPelangganCari"); // NOI18N
        txtPelangganCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPelangganCariActionPerformed(evt);
            }
        });
        txtPelangganCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPelangganCariKeyPressed(evt);
            }
        });
        add(txtPelangganCari);
        txtPelangganCari.setBounds(160, 10, 76, 21);

        txtNamaPelangganCari.setFont(resourceMap.getFont("txtPelangganCari.font")); // NOI18N
        txtNamaPelangganCari.setText(resourceMap.getString("txtNamaPelangganCari.text")); // NOI18N
        txtNamaPelangganCari.setName("txtNamaPelangganCari"); // NOI18N
        add(txtNamaPelangganCari);
        txtNamaPelangganCari.setBounds(240, 10, 380, 21);

        jLabel1.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(10, 70, 130, 15);

        cboBulanCari.setFont(resourceMap.getFont("cboBulanCari.font")); // NOI18N
        cboBulanCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cboBulanCari.setName("cboBulanCari"); // NOI18N
        add(cboBulanCari);
        cboBulanCari.setBounds(160, 40, 140, 21);

        txtTahun.setFont(resourceMap.getFont("cboBulanCari.font")); // NOI18N
        txtTahun.setText(resourceMap.getString("txtTahun.text")); // NOI18N
        txtTahun.setName("txtTahun"); // NOI18N
        add(txtTahun);
        txtTahun.setBounds(300, 40, 72, 21);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(630, 10, 120, 50);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(10, 41, 113, 15);

        TanggalCair.setFieldFont(resourceMap.getFont("TanggalCair.dch_combo_fieldFont")); // NOI18N
        add(TanggalCair);
        TanggalCair.setBounds(160, 70, 160, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtPelangganCari.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Data Pelanggan.. !");
            txtPelangganCari.requestFocus();
        } else {
            reloaddatacair();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPelangganCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPelangganCariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPelangganCariActionPerformed

    private void txtPelangganCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPelangganCariKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pelangganDao bDao;
            List<List<Object>> rows = new ArrayList<List<Object>>();
            String where = "STATUSAKTIF='0' AND KODEPELANGGAN like '" + txtPelangganCari.getText() + "%' OR lower(NAMA) like '%" + txtPelangganCari.getText() + "%'";
            List<pelanggan> pelangganList;
            List<Object> newRow;
            
            try {
                Connection c = koneksi.getKoneksiJ();
                bDao = new pelangganDao(c);
                pelangganList = bDao.getAllFilter(where, 100);
                String header[] = {"Kode", "Nama Pelanggan"};
                for (ListIterator<pelanggan> it = pelangganList.listIterator(); it.hasNext();) {
                    pelanggan n = it.next();
                    newRow = new ArrayList<Object>();
                    newRow.add(n.getKODEPELANGGAN());
                    newRow.add(n.getNAMA());
                    rows.add(newRow);
                }
                ArrayTable a;
                a = new ArrayTable(header, rows);
                jScrollPane2.getViewport().remove(tabelPelanggan);
                tabelPelanggan = new JTable(a);
                tabelPelanggan.setFont(new Font("Tahoma", Font.BOLD, 12));
                tabelPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        tabelPelangganKeyPressed(evt);
                    }
                });
                jScrollPane2.getViewport().add(tabelPelanggan);
                jScrollPane2.repaint();
                c.close();
            } catch (SQLException ex) {

            } 
            jScrollPane2.setVisible(true);
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            jScrollPane2.setVisible(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tabelPelanggan.requestFocus();
            tabelPelanggan.getSelectionModel().setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_txtPelangganCariKeyPressed

    private void tabelPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelPelangganKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPelangganCari.setText(tabelPelanggan.getValueAt(tabelPelanggan.getSelectedRow(), 0).toString());
            txtNamaPelangganCari.setText(tabelPelanggan.getValueAt(tabelPelanggan.getSelectedRow(), 1).toString());
            jScrollPane2.setVisible(false);
            txtNamaPelangganCari.requestFocus();
        }
    }//GEN-LAST:event_tabelPelangganKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo TanggalCair;
    private javax.swing.JComboBox cboBulanCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelData;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTextField txtNamaPelangganCari;
    private javax.swing.JTextField txtPelangganCari;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables

    public void angsuranPiutang(Connection c) {
        controller.angsuranPiutang(c,this);
    }
    
    public void reloaddatacair(){        
        List<List<Object>> rows;
            String sql = "select g.ID, g.NOMORGIRO, g.TGLGIRO, g.TGLJTEMPO, g.JUMLAH, case g.STATUS when 0 then 'Open' when 1 then 'Cair' when 2 then 'Batal' end as Status from GIRO g \n"
                    + "inner join PELANGGAN p on g.KODEPELANGGAN = p.KODEPELANGGAN\n"
                    + "inner join BANK b on g.IDBANK = b.IDBANK "
                    + "WHERE g.kodepelanggan = '" + txtPelangganCari.getText() + "' "
                    + "AND MONTH(g.TGLGIRO)=" + (cboBulanCari.getSelectedIndex() + 1) + " "
                    + "AND YEAR(g.TGLGIRO)=" + txtTahun.getText() + "";
            try {
                Connection c = koneksi.getKoneksiJ();
                rows = ExecuteQuery.Query(c, sql);
                String header[] = {"ID", "NOMOR GIRO", "TGL GIRO", "TGL JATUH TEMPO", "JUMLAH", "STATUS"};
                ArrayTable a;
                a = new ArrayTable(header, rows);
                jScrollPane1.getViewport().remove(tabelData);
                tabelData = new JTable(a);
                tabelData.getColumnModel().getColumn(4).setCellRenderer(new DecimalFormatRenderer());
                tabelData.setFont(new Font("Tahoma", Font.BOLD, 12));

                jScrollPane1.getViewport().add(tabelData);
                jScrollPane1.repaint();
                c.close();
            } catch (SQLException ex) {
                Logger.getLogger(GiroBayarView.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public void updateStatusBatal(Connection c){
        controller.updateStatusBatal(c,this); 
    }
}
