/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erv.view;

import com.erv.controller.GiroKeluarController;
import com.erv.db.koneksi;
import com.erv.db.supplierDao;
import com.erv.function.ArrayTable;
import com.erv.function.ExecuteQuery;
import com.erv.fungsi.DecimalFormatRenderer;
import com.erv.model.GiroKeluarModel;
import com.erv.model.supplier;
import datechooser.beans.DateChooserCombo;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.net.ConnectException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author ervan
 */
public class GiroKeluarBayarView extends javax.swing.JPanel {

    /**
     * Creates new form GiroBayarView
     */
    SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
    com.erv.function.Util u = new com.erv.function.Util();
    GiroKeluarModel model;
    GiroKeluarController controller;
    public GiroKeluarBayarView() {
        model = new GiroKeluarModel();
        controller = new GiroKeluarController();
        initComponents();
        cboBulanCari.setSelectedIndex(u.blnsekarang - 1);
        txtTahun.setText("" + u.thnsekarang);
        TanggalCair.setDateFormat(df); 
        jScrollPane2.setVisible(false);
    }

    public JTable getTabelData() {
        return tabelData;
    }

    public void setTabelData(JTable tabelData) {
        this.tabelData = tabelData;
    }

    public DateChooserCombo getTanggalCair() {
        return TanggalCair;
    }

    public void setTanggalCair(DateChooserCombo TanggalCair) {
        this.TanggalCair = TanggalCair;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        txtSupplierCari = new javax.swing.JTextField();
        txtNamaSupplierCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboBulanCari = new javax.swing.JComboBox();
        txtTahun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TanggalCair = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(null);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(GiroKeluarBayarView.class);
        tabelPelanggan.setFont(resourceMap.getFont("tabelPelanggan.font")); // NOI18N
        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelPelanggan.setName("tabelPelanggan"); // NOI18N
        tabelPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelPelangganKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        add(jScrollPane2);
        jScrollPane2.setBounds(130, 40, 470, 170);

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(10, 10, 70, 15);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabelData.setFont(resourceMap.getFont("tabelData.font")); // NOI18N
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelData.setName("tabelData"); // NOI18N
        jScrollPane1.setViewportView(tabelData);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 106, 810, 380);

        txtSupplierCari.setText(resourceMap.getString("txtSupplierCari.text")); // NOI18N
        txtSupplierCari.setName("txtSupplierCari"); // NOI18N
        txtSupplierCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCariActionPerformed(evt);
            }
        });
        txtSupplierCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierCariKeyPressed(evt);
            }
        });
        add(txtSupplierCari);
        txtSupplierCari.setBounds(130, 10, 76, 26);

        txtNamaSupplierCari.setFont(resourceMap.getFont("txtNamaSupplierCari.font")); // NOI18N
        txtNamaSupplierCari.setText(resourceMap.getString("txtNamaSupplierCari.text")); // NOI18N
        txtNamaSupplierCari.setName("txtNamaSupplierCari"); // NOI18N
        add(txtNamaSupplierCari);
        txtNamaSupplierCari.setBounds(215, 11, 360, 21);

        jLabel1.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(10, 70, 100, 15);

        cboBulanCari.setFont(resourceMap.getFont("cboBulanCari.font")); // NOI18N
        cboBulanCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cboBulanCari.setName("cboBulanCari"); // NOI18N
        add(cboBulanCari);
        cboBulanCari.setBounds(130, 40, 140, 21);

        txtTahun.setFont(resourceMap.getFont("txtTahun.font")); // NOI18N
        txtTahun.setText(resourceMap.getString("txtTahun.text")); // NOI18N
        txtTahun.setName("txtTahun"); // NOI18N
        add(txtTahun);
        txtTahun.setBounds(280, 38, 72, 21);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(580, 10, 140, 50);

        TanggalCair.setFieldFont(resourceMap.getFont("TanggalCair.dch_combo_fieldFont")); // NOI18N
        add(TanggalCair);
        TanggalCair.setBounds(130, 70, 150, 26);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(10, 41, 70, 15);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reloadgirobayar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSupplierCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSupplierCariActionPerformed

    private void txtSupplierCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCariKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<List<Object>> rows = new ArrayList<List<Object>>();
            String where = "IDSUPPLIER like '" + txtSupplierCari.getText() + "%' OR lower(NAMA) like '%" + txtSupplierCari.getText() + "%'";
            List<supplier> supList;
            List<Object> newRow;
            try {
                Connection c = koneksi.getKoneksiJ();
                supList = supplierDao.getAllFilter(c,where,100);
                c.close();
                String header[] = {"Kode", "Nama Supplier"};
                for (ListIterator<supplier> it = supList.listIterator(); it.hasNext();) {
                    supplier n = it.next();
                    newRow = new ArrayList<Object>();
                    newRow.add(n.getIDSUPPLIER());
                    newRow.add(n.getNAMA());
                    rows.add(newRow);
                }
                ArrayTable a;
                a = new ArrayTable(header, rows);
                jScrollPane2.getViewport().remove(tabelPelanggan);
                tabelPelanggan = new JTable(a);
                tabelPelanggan.setFont(new Font("Tahoma", Font.BOLD, 12));
                tabelPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
                    @Override
                    public void keyPressed(java.awt.event.KeyEvent evt) {
                        tabelPelangganKeyPressed(evt);
                    }
                });
                jScrollPane2.getViewport().add(tabelPelanggan);
                jScrollPane2.repaint();
            } catch (SQLException ex) {

            } 
            jScrollPane2.setVisible(true);
        } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            jScrollPane2.setVisible(false);
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tabelPelanggan.requestFocus();
            tabelPelanggan.getSelectionModel().setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_txtSupplierCariKeyPressed

    private void tabelPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelPelangganKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSupplierCari.setText(tabelPelanggan.getValueAt(tabelPelanggan.getSelectedRow(), 0).toString());
            txtNamaSupplierCari.setText(tabelPelanggan.getValueAt(tabelPelanggan.getSelectedRow(), 1).toString());
            jScrollPane2.setVisible(false);
            txtNamaSupplierCari.requestFocus();
        }
    }//GEN-LAST:event_tabelPelangganKeyPressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo TanggalCair;
    private javax.swing.JComboBox cboBulanCari;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelData;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTextField txtNamaSupplierCari;
    private javax.swing.JTextField txtSupplierCari;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables

    public void angsuranHutang(){
        controller.angsuranHutang(this); 
    }
    
    public void updateStatusBatal(){
        controller.updateStatusBatal(this); 
        reloadgirobayar();
    }
    
    public void reloadgirobayar(){
        List<List<Object>> rows ;
        String sql = "select gk.ID,gk.NOMORGIRO,gk.TGLGIRO,TGLJTEMPO,JUMLAH,case gk.STATUS "
                + "when 0 then 'Open' when 1 then 'Cair' when 2 then 'Batal' end as Status "
                + "from GIROKELUAR gk inner join SUPPLIER sp on gk.KODESUPPLIER = sp.IDSUPPLIER " 
                + "WHERE sp.IDSUPPLIER = '"+txtSupplierCari.getText()+"' "
                + "AND MONTH(gk.TGLGIRO)="+(cboBulanCari.getSelectedIndex()+1)+" "
                + "AND YEAR(gk.TGLGIRO)="+ txtTahun.getText()+"";
        try {
            Connection c = koneksi.getKoneksiJ();
            rows = ExecuteQuery.Query(c, sql);
            c.close();
            String header[] = {"ID","NOMOR GIRO", "TGL GIRO", "TGL JATUH TEMPO", "JUMLAH", "STATUS"};
            ArrayTable a;
            a = new ArrayTable(header, rows);
            jScrollPane1.getViewport().remove(tabelData);
            tabelData = new JTable(a);
            tabelData.getColumnModel().getColumn(4).setCellRenderer(new DecimalFormatRenderer());
            tabelData.setFont(new Font("Tahoma", Font.BOLD, 12));
            
            jScrollPane1.getViewport().add(tabelData);
            jScrollPane1.repaint();
            
        } catch (SQLException ex) {
            Logger.getLogger(GiroKeluarBayarView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
