/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * FormPelanggan.java
 *
 * Created on Nov 25, 2011, 5:11:03 AM
 */
package com.eigher.form;

import javariesoft.*;
import com.erv.db.koneksi;
import com.eigher.db.usertableDao;
import com.erv.function.JDBCAdapter;
import com.eigher.model.usertable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import java.awt.Font;
import java.text.SimpleDateFormat;
import javax.swing.table.TableColumn;

/**
 *
 * @author erwadi
 */
public class FKontrolJurnalHutangBayar extends javax.swing.JInternalFrame {
    Connection c;
    Connection cm;
    Statement statm;
    usertable ut;
    usertableDao utdao;
    com.erv.function.Util u = new com.erv.function.Util();
    java.text.DateFormat d = new SimpleDateFormat("yyyy-MM-dd");

    /** Creates new form FormPelanggan */
    public FKontrolJurnalHutangBayar() {
        initComponents();
        try {
            c = koneksi.getKoneksiJ();
            ut = new usertable();
            utdao = new usertableDao();
            tgl1.setDateFormat(d);
            tgl2.setDateFormat(d);
            reloadUser();
            buatTabel();
        } catch (SQLException ex) {
            Logger.getLogger(FKontrolJurnalHutangBayar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCool1 = new com.erv.function.PanelCool();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFilter = new javax.swing.JButton();
        lblKodeAkun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox();
        tgl1 = new datechooser.beans.DateChooserCombo();
        tgl2 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setClosable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FKontrolJurnalHutangBayar.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelCool1.setName("panelCool1"); // NOI18N
        panelCool1.setLayout(null);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        panelCool1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 960, 520);

        btnFilter.setFont(resourceMap.getFont("btnFilter.font")); // NOI18N
        btnFilter.setIcon(resourceMap.getIcon("btnFilter.icon")); // NOI18N
        btnFilter.setText(resourceMap.getString("btnFilter.text")); // NOI18N
        btnFilter.setName("btnFilter"); // NOI18N
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        panelCool1.add(btnFilter);
        btnFilter.setBounds(480, 20, 110, 25);

        lblKodeAkun.setFont(resourceMap.getFont("lblKodeAkun.font")); // NOI18N
        lblKodeAkun.setForeground(resourceMap.getColor("lblKodeAkun.foreground")); // NOI18N
        lblKodeAkun.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKodeAkun.setName("lblKodeAkun"); // NOI18N
        panelCool1.add(lblKodeAkun);
        lblKodeAkun.setBounds(420, 240, 230, 20);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        panelCool1.add(jLabel3);
        jLabel3.setBounds(300, 20, 30, 16);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        panelCool1.add(jLabel4);
        jLabel4.setBounds(40, 50, 110, 16);

        cmbUser.setFont(resourceMap.getFont("cmbUser.font")); // NOI18N
        cmbUser.setName("cmbUser"); // NOI18N
        panelCool1.add(cmbUser);
        cmbUser.setBounds(160, 50, 310, 21);

        tgl1.setFieldFont(resourceMap.getFont("tgl1.dch_combo_fieldFont")); // NOI18N
        panelCool1.add(tgl1);
        tgl1.setBounds(160, 20, 130, 20);

        tgl2.setFieldFont(resourceMap.getFont("tgl2.dch_combo_fieldFont")); // NOI18N
        panelCool1.add(tgl2);
        tgl2.setBounds(330, 20, 140, 20);

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        panelCool1.add(jLabel5);
        jLabel5.setBounds(40, 20, 110, 16);

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelCool1.add(btnExit);
        btnExit.setBounds(480, 50, 110, 23);

        getContentPane().add(panelCool1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-991)/2, (screenSize.height-648)/2, 991, 648);
    }// </editor-fold>//GEN-END:initComponents

private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
// TODO add your handling code here:

    reloadData();
}//GEN-LAST:event_btnFilterActionPerformed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jTable1MouseClicked

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btnExitActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(FKontrolJurnalHutangBayar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox cmbUser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblKodeAkun;
    private com.erv.function.PanelCool panelCool1;
    private datechooser.beans.DateChooserCombo tgl1;
    private datechooser.beans.DateChooserCombo tgl2;
    // End of variables declaration//GEN-END:variables

    void reloadData() {
        try {
            JDBCAdapter j = new JDBCAdapter(c);
            //String period = txtTahun.getText() + "." + (cboBulan.getSelectedIndex() + 1);
            String sql = "SELECT * FROM LOGHISTORY where TANGGAL>='" + tgl1.getText() + "' and TANGGAL<='" + tgl2.getText() + "' AND USERIDENTITY='" + cmbUser.getSelectedItem() + "'";
            j.executeQuery(sql);
            jScrollPane2.getViewport().remove(jTable1);
            jTable1 = new JTable(j);
            TableColumn col = jTable1.getColumnModel().getColumn(0);
            col.setPreferredWidth(6);
            col = jTable1.getColumnModel().getColumn(1);
            col.setPreferredWidth(20);
            col = jTable1.getColumnModel().getColumn(2);
            col.setPreferredWidth(15);
            col = jTable1.getColumnModel().getColumn(3);
            col.setPreferredWidth(15);
            col = jTable1.getColumnModel().getColumn(4);
            col.setPreferredWidth(20);
            col = jTable1.getColumnModel().getColumn(5);
            col.setPreferredWidth(20);
            col = jTable1.getColumnModel().getColumn(6);
            col.setPreferredWidth(20);
            col = jTable1.getColumnModel().getColumn(7);
            col.setPreferredWidth(500);
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {

                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTable1MouseClicked(evt);
                }
            });
            jTable1.setFont(new Font("Tahoma", Font.BOLD, 11));
            jScrollPane2.getViewport().add(jTable1);
            jScrollPane2.repaint();
        } catch (Exception ex) {
            Logger.getLogger(FKontrolJurnalHutangBayar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void reloadUser() {
        cmbUser.removeAllItems();
        //cboBank.removeAllItems();
        String sql = "select USERIDENTITY from USERTABLE where USERIDENTITY<>'helfazahar'";
        try {
            Statement stat = c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery(sql);

            int j = 0;
            if (rs.last()) {
                j = rs.getRow();
            }
            if (j > 0) {
                rs.beforeFirst();
                int c = 0;
                while (rs.next()) {
                    cmbUser.addItem(rs.getString(1));
                    c++;
                }
            }
            rs.close();
            stat.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormJurnal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void buatTabel() {

        String sqlJurnal = "CREATE TABLE HUTANGBAYAR (\n"
                + "    `ID` INT(10) primary key ,\n"
                + "    `KODEHUTANGBAYAR` VARCHAR(20),\n"
                + "    `IDHUTANG` INT(10) unique,\n"
                + "    `TANGGAL` DATE,\n"
                + "    `JUMLAH` DOUBLE(17),\n"
                + "    `REF` VARCHAR(20) DEFAULT '0',\n"
                + "    STATUS varchar(1) DEFAULT '0');";
        //String sqlDO = "create table dopenjualan(IDPENJUALAN int,IDDO int, KODEBARANG varchar(20))";
        try {
            statm.execute(sqlJurnal);
            //  stat.execute(sqlDO);
        } catch (SQLException ex) {
        }
    }
}
