/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormLogin.java
 *
 * Created on Mar 13, 2012, 10:56:50 PM
 */
package com.eigher.form;

import com.erv.db.koneksi;
import com.eigher.db.usertableDao;
import com.eigher.model.usertable;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.eigher.db.loghistoryDao;
import com.eigher.model.loghistory;
import javariesoft.JavarieSoftApp;
import javariesoft.JavarieSoftView;

/**
 *
 * @author eigher
 */
public class FormLogin extends javax.swing.JInternalFrame {

    usertable ut;
    usertableDao utdao;
    //Connection c;
    loghistory lh;
    loghistoryDao lhdao;
    com.erv.function.Util u = new com.erv.function.Util();
    String aksilog = "";

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        Connection c = null;
        try {
            kosong();
            c = koneksi.getKoneksiJ();
            ut = new usertable();
            utdao = new usertableDao();
            lh = new loghistory();
            lhdao = new loghistoryDao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }finally {
            if (c != null) {
                try {
                    c.close();
                } catch (SQLException ex) {
                    Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelCool1 = new com.erv.function.PanelCool();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(javariesoft.JavarieSoftApp.class).getContext().getResourceMap(FormLogin.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        setClosable(true);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        panelCool1.setName("panelCool1"); // NOI18N
        panelCool1.setLayout(null);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelCool1.add(jLabel2);
        jLabel2.setBounds(40, 80, 90, 15);

        jLabel3.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        panelCool1.add(jLabel3);
        jLabel3.setBounds(40, 50, 90, 15);

        txtUsername.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        txtUsername.setText(resourceMap.getString("txtUsername.text")); // NOI18N
        txtUsername.setName("txtUsername"); // NOI18N
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        panelCool1.add(txtUsername);
        txtUsername.setBounds(140, 50, 180, 21);

        txtPassword.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        txtPassword.setText(resourceMap.getString("txtPassword.text")); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        panelCool1.add(txtPassword);
        txtPassword.setBounds(140, 80, 180, 21);

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setIcon(resourceMap.getIcon("btnExit.icon")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelCool1.add(btnExit);
        btnExit.setBounds(190, 120, 130, 40);

        btnLogin.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnLogin.setIcon(resourceMap.getIcon("btnLogin.icon")); // NOI18N
        btnLogin.setText(resourceMap.getString("btnLogin.text")); // NOI18N
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelCool1.add(btnLogin);
        btnLogin.setBounds(40, 120, 120, 40);

        getContentPane().add(panelCool1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 386, 210);
    }// </editor-fold>//GEN-END:initComponents

private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    Connection c = null;
    try {
        // TODO add your handling code here:
        c = koneksi.getKoneksiJ();
        if (utdao.cekdata(c, txtUsername.getText(), txtPassword.getText())) {
            ut = utdao.getDetails(c, txtUsername.getText());
            JavarieSoftApp.jenisuser = ut.getUSERIDENTITY();
            JavarieSoftApp.groupuser = ut.getGROUPUSER();
//            if (ut.getGROUPUSER().equals("Pembelian")) {
//
//                JavarieSoftView.pembelianakses();
//                       //Dean.pembelianakses();
//                //jenisuser="Pembelian";
//            } else 
//                if (ut.getGROUPUSER().equals("Penjualan")) {
//                JavarieSoftView.penjualanakses();
//                //Dean.penjualanakses();
//            } else 
            if (ut.getGROUPUSER().equals("Pajak")) {
                JavarieSoftView.pajakakses();
                //Dean.pajakakses();
            } else if (ut.getGROUPUSER().equals("Accounting")) {
                JavarieSoftView.accountingakses();
                //Dean.accountingakses(); 
            } else if (ut.getGROUPUSER().equals("Administrator")) {
                JavarieSoftView.aktif();
                //Dean.aktif();
            } else if (ut.getGROUPUSER().equals("Apoteker")) {
                JavarieSoftView.apotekerakses();
                //Dean.pembelianakses();
            } else if (ut.getGROUPUSER().equals("SUPERUSER")) {
                JavarieSoftView.aktif();
                //Dean.aktif();
            } else if (ut.getGROUPUSER().equals("Operator")) {
                JavarieSoftView.operatorakses();
                //Dean.aktif();
            } else if (ut.getGROUPUSER().equals("General")) {
                JavarieSoftView.generalakses();
                //Dean.aktif();
            } else if (ut.getGROUPUSER().equals("Asisten Administrator")) {
                JavarieSoftView.asistenadminakses();
                //Dean.aktif();
            }  else if (ut.getGROUPUSER().equals("Master Data")) {
                JavarieSoftView.masterdataakses();
                //Dean.aktif();
            }
            aksilog = "LogIn";
            prosesUpdateLog(c);
            JOptionPane.showMessageDialog(null, "Log In Success ..!");
            JavarieSoftView.LblJenis.setText(JavarieSoftApp.jenisuser);
            JavarieSoftView.Lblgroup.setText(JavarieSoftApp.groupuser);
                    //Dean.LblJenis.setText(JavarieSoftApp.jenisuser);
            //Dean.Lblgroup.setText(JavarieSoftApp.groupuser);
            JavarieSoftView.panelCool1.invalidate();
            JavarieSoftView.panelCool1.repaint();
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Username Dan Password Tidak Benar..!");
            txtUsername.requestFocus();
        }

    } catch (SQLException ex) {
        Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
    }finally {
        if (c != null) {
            try {
                c.close();
            } catch (SQLException ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}//GEN-LAST:event_btnLoginActionPerformed

private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
// TODO add your handling code here:
    dispose();
}//GEN-LAST:event_btnExitActionPerformed

private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == 10) {
        txtPassword.requestFocus();
    }
}//GEN-LAST:event_txtUsernameKeyPressed

private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
// TODO add your handling code here:
    if (evt.getKeyCode() == 10) {
        btnLogin.requestFocus();
    }
}//GEN-LAST:event_txtPasswordKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.erv.function.PanelCool panelCool1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
void kosong() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtUsername.requestFocus();
    }

    void prosesUpdateLog(Connection c) throws SQLException{
        //java.sql.Date tanggallog;
        String tanggallog;
        String jamlog = u.jamsekarang + ":" + u.menitsekarang + ":" + u.detiksekarang;
        //tanggallog = java.sql.Date.valueOf(u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang);
        tanggallog = u.thnsekarang + "-" + u.blnsekarang + "-" + u.tglsekarang;

        try {
            String ketlog = "";
            lh.setUSERIDENTITY(JavarieSoftApp.jenisuser);
            lh.setTANGGAL(tanggallog);
            lh.setJAM(jamlog);
            lh.setTABEL("TUSERTABLE");
            lh.setNOREFF(txtUsername.getText());
            lh.setAKSI(aksilog);
            if (aksilog.equals("LogIn")) {
                ketlog = "Log In User " + txtUsername.getText() + " Hak Akses " + JavarieSoftApp.groupuser;
            }
            lh.setKETERANGAN(ketlog);
            lhdao.insert(c, lh);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

    }
}
